### ISSUE TITLE
Missing regions key

### ISSUE THREAD

**Issue by rokcarl** [nccgroup/Scout2#100]
I get the following error:

    python Scout2.py
    Fetching CloudTrail config...
    Fetching EC2 config...
                  region   Elastic LBs   Elastic IPs          VPCs   Sec. Groups     Instances
          ap-southeast-1           0/0           0/0           1/1           1/1           0/0
               us-west-2           0/0           0/0           1/1           1/1           0/0
               sa-east-1           0/0           0/0           1/1           1/1           0/0
               eu-west-1           0/0           0/0           1/1           1/1           0/0
              ap-south-1           0/0           0/0           1/1           1/1           0/0
               us-east-1           0/1         21/21           5/4         13/13         28/28
          ap-northeast-1           0/0           0/0           1/1           1/1           0/0
            eu-central-1           0/0           0/0           1/1           1/1           0/0
          ap-northeast-2           0/0           0/0           1/1           1/1           0/0
          ap-southeast-2           0/0           0/0           1/1           1/1           0/0
               us-west-1           0/0           0/0           0/0           1/1           0/0
    Fetching IAM users...
    107/107
    Fetching IAM groups...
    4/4
    Fetching IAM roles...
    2/2
    Fetching IAM policies...
    10/10
    Fetching IAM credential report...
    Fetching IAM password policy...
    Fetching RDS config...
    Fetching Redshift config...
    Fetching S3 buckets config...
    157/157
    Analyzing VPC config...
    Parsing EC2 instances...
    Parsing ELBs...
    Parsing Redshift clusters...
    Parsing RDS instances...
    Analyzing EC2 config... Success
    Analyzing AWS config...
    Traceback (most recent call last):
      File "/usr/src/app/Scout2/AWSScout2/utils.py", line 269, in create_report_metadata
        manage_dictionary(aws_config['metadata'][s]['resources'][resource], 'risks', [])
    KeyError: 'regions'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "Scout2.py", line 267, in <module>
        sys.exit(main(args))
      File "Scout2.py", line 204, in main
        create_report_metadata(aws_config, services)
      File "/usr/src/app/Scout2/AWSScout2/utils.py", line 272, in create_report_metadata
        manage_dictionary(aws_config['metadata'][s]['summaries'][resource], 'risks', [])
    KeyError: 'summaries'

**Comment by lymichaels** [comment]
I get the same error was well...

**Comment by l01cd3v** [comment]
Can you please run the tool with --debug? It will give me more information about what rule is failing. Thanks

**Comment by l01cd3v** [comment]
Closing for now
