### ISSUE TITLE
Failed to process rule defined in iam-inline-group-policy-allows-sts-AssumeRole.json

### ISSUE THREAD

**Issue by vitalisec** [nccgroup/Scout2#102]
Analyzing AWS config...
sts:AssumeRole
string indices must be integers
sts:AssumeRole

Failed to process rule defined in iam-inline-group-policy-allows-sts-AssumeRole.json

Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 176, in main
    aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
KeyError: 'items'

**Comment by l01cd3v** [comment]
Merged PR #106, I *think* this should be fixed in master  now.
