### ISSUE TITLE
KeyError: u'summaries'

### ISSUE THREAD

**Issue by jpoling-dswrx** [nccgroup/Scout2#103]
> # python Scout2.py 
Fetching Redshift config...
Fetching S3 buckets config...
1/1
Fetching RDS config...
Fetching IAM users...
14/14
Fetching IAM groups...
4/4
Fetching IAM roles...
9/9
Fetching IAM policies...
11/11
Fetching IAM credential report...
Fetching IAM password policy...
Fetching EC2 config...
...
Fetching CloudTrail config...
Analyzing VPC config...
Parsing EC2 instances...
Parsing ELBs...
Parsing Redshift clusters...
Parsing RDS instances...
Analyzing EC2 config... Success
Analyzing AWS config...
Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 204, in main
    create_report_metadata(aws_config, services)
  File "/home/ec2-user/venv_Scout2/Scout2/AWSScout2/utils.py", line 272, in create_report_metadata
    manage_dictionary(aws_config['metadata'][s]['summaries'][resource], 'risks', [])
KeyError: u'summaries'

Any ideas on what could be the issue here?

**Comment by isaacbentley** [comment]
+1

Same issue

**Comment by isaacbentley** [comment]
If i comment out the following, it seems to work:
_./Scout2/AWSScout2/utils.py", starting at line 267_
```
                #if aws_config['services'][s]['violations'][v]['flagged_items'] > 0:
                #    try:
                #        manage_dictionary(aws_config['metadata'][s]['resources'][resource], 'risks', [])
                #        aws_config['metadata'][s]['resources'][resource]['risks'].append(v)
                #    except Exception as e:
                #        manage_dictionary(aws_config['metadata'][s]['summaries'][resource], 'risks', [])
                #        aws_config['metadata'][s]['summaries'][resource]['risks'].append(v)
```

**Comment by l01cd3v** [comment]
I just pushed new code that may fix the issue. Can you pull and give it a try? If the issue still exists, can you run the tool with --debug and share the log? Thanks

**Comment by isaacbentley** [comment]
I just tried, seems like it works now ;-)

**Comment by l01cd3v** [comment]
Thanks !
