### ISSUE TITLE
KeyError:'items' 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [nccgroup/Scout2#104]
Fetching CloudTrail config...
('Connection aborted.', error(65, 'No route to host'))
('Connection aborted.', error(65, 'No route to host'))
('Connection aborted.', error(65, 'No route to host'))
Fetching EC2 config...
              region   Elastic LBs   Elastic IPs          VPCs   Sec. Groups     Instances
          ap-south-1             0           0/0           1/1           1/1           0/0('Connection aborted.', error(65, 'No route to host'))
          ap-south-1             0           0/0           1/1           1/1           0/0
           us-east-1           0/8         35/35           4/4         53/53         61/61
      ap-northeast-1           0/0           0/0           0/0           1/1           0/0
           eu-west-1           0/0           0/0           0/0           1/1           0/0
      ap-northeast-2           0/0           0/0           1/1           1/1           0/0
      ap-southeast-1           0/0           0/0           0/0           1/1           0/0
      ap-southeast-2           0/0           0/0           1/0           1/1           0/0
           us-west-2           0/0           2/2           2/1           2/2           0/0
           us-west-1           0/1           4/4           3/2         11/11           5/5
        eu-central-1           0/0           4/4           3/2         11/11           5/5('Connection aborted.', error(65, 'No route to host'))
('Connection aborted.', error(65, 'No route to host'))
('Connection aborted.', error(65, 'No route to host'))
('Connection aborted.', error(65, 'No route to host'))
        eu-central-1           0/0           4/4           3/2         11/11           5/5
           sa-east-1           0/0           0/0           1/0           1/1           0/0
Fetching IAM users...
83/83
Fetching IAM groups...
16/16
Fetching IAM roles...
28/28
Fetching IAM policies...
31/31
Fetching IAM credential report...
Fetching IAM password policy...
Fetching RDS config...
Fetching Redshift config...
Fetching S3 buckets config...
97/97
Analyzing VPC config...
Parsing EC2 instances...
Parsing ELBs...
Parsing Redshift clusters...
Parsing RDS instances...
Analyzing EC2 config... Success
Analyzing AWS config...
{'trails': {}, 'name': u'us-west-1'}
u'trails_count'
{'trails': {}, 'name': u'us-west-1'}

Failed to process rule defined in cloudtrail-not-configured.json

Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 176, in main
    aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
KeyError: 'items'

^ Getting this error while could run audit if run through old cloned code.

**Comment by l01cd3v** [comment]
This should be fixed in master now

**Comment by l01cd3v** [comment]
Closing for now, please re-open if the issue remains.
