### ISSUE TITLE
report.html has incorrect paths for JS and CSS?

### ISSUE THREAD

**Issue by jutulen** [nccgroup/Scout2#111]
I really like this tool, if I can get it working it will be perfect for my project, but I'm having some problems getting it to work right.

All the include paths for the javascript and CSS appear to be incorrect?

I only got the /html/report.html file to load if I modified the paths by adding "../" at the front of the path, for example: 

    <link href="../inc-bootstrap/css/bootstrap.min.css" rel="stylesheet">

But even after I modified all the paths the report page still won't load completely.
The top nav bar is there but the drop-downs don't work.

There appears to be a bug in scout2.js on this line (63):
var template_to_compile = document.getElementById(id1).innerHTML;
throws an error: 
scout2.js:63 Uncaught TypeError: Cannot read property 'innerHTML' of null

When I change line 63 to:
var template_to_compile = id1;
I'm able to load the page without any more javascript or CSS errors.

But the only thing shown on the page is:
last_run.details.templateservices.id.violations.details.template

Please help?

**Comment by w1bble** [comment]
Similar issue with multiple sub-folder reports for multiple creds, the reportname.html in subfolders, moving them up displays results / css .. is there an easy fix? (or method to export the html so I can easily share results).

**Comment by l01cd3v** [comment]
@jutulen The html folder contains templates and files that are used to build the final report. You need to open the report.hml or report-<profilename>.html in the root folder of the repo.  This file doesn't exist until you run ./Scout2.py

**Comment by l01cd3v** [comment]
@w1bble Seems like you're asking for a way to create a standalone report, similar to issue #84

**Comment by w1bble** [comment]
sort of, I have multiple identities and when invoking Scout.py --profile example/user the reports are dropped into a subfolder without inheriting the css which then needs to be either moved to the root folder to display properly or the inc* folders copied to subfolder.

**Comment by l01cd3v** [comment]
@w1bble , I see. I'll push a fix to replace / and \ in profile names with a - or _ most likely.

**Comment by l01cd3v** [comment]
@w1bble This should be fixed in the dev branch now. Can you confirm? I'll merge dev into master soon

**Comment by w1bble** [comment]
Dev branch is fixed (tried for a couple of accounts and the underscore is a big improvement rather than sub dir; thanks

**Comment by jutulen** [comment]
@l01cd3v now I see! Doh! 

I just ran the script and the reports display correctly. 

Any chance you could rename the template file to something else like _report.html to disambiguate the files from each other?

Also, could you please add a little more detail in the instructions on running the script?
To me it would be useful to mention that inc-awsconfig/aws_config.js and report.html are generated each time the script is run and that it will overwrite any previous reports.

Thanks for the quick response, I really appreciate it. 

This tool is going to make my project a lot easier, thank you!

**Comment by l01cd3v** [comment]
@jutulen , cool thanks for confirming.

Documentation has been on my plate for a while but unfortunately I have limited resources so new features and bug fixes take priority. I'll def consider renaming the html folder to something less ambiguous. Thanks for the feedback.
