### ISSUE TITLE
Compliant with AWS Rules on Scanning?

### ISSUE THREAD

**Issue by rjhintz** [nccgroup/Scout2#114]
It would be helpful to have a positive statement in the README, which might be something like:

"Compliant with current AWS restrictions on customer security scanning."

Based on a [Reddit comment](https://www.reddit.com/r/aws/comments/5azvwn/scout2_security_auditing_tool_for_aws_environments/d9lay1h/)

**Comment by l01cd3v** [comment]
Done

**Comment by rjhintz** [comment]
Thanks. I know it can be annoying to have randos show up and post issues that seem trivial. I appreciate your willingness to deal with them.
