### ISSUE TITLE
Audit other accounts?

### ISSUE THREAD

**Issue by rjhintz** [nccgroup/Scout2#115]
If so, how?

If not, please consider as an enhancement.

Passing on from a [Reddit comment](https://www.reddit.com/r/aws/comments/5azvwn/scout2_security_auditing_tool_for_aws_environments/d9l4z9d/).

**Comment by l01cd3v** [comment]
Indeed. It was always possible but not easy to do. With the latest code, it should work seamlessly.

Assuming you're authorized to assume a role and configured it as follow (same as CLI) in the ~/.aws/config file:
[profile name-using-role]
role_arn = arn:aws:iam::TARGET_ACCOUNT_ID:role/TARGET_ROLE
source_profile = NAME_OF_PROFILE_AUTHORIZED_TO_ASSUME_ROLE

If you have valid credentials for the source profile, Scout2 will make the assume role call (similar to AWS CLI) and use the role's STS credentials to make the run.

**Comment by l01cd3v** [comment]
You'll need to pull the latest code and install the latest version of opinel
