### ISSUE TITLE
S3 tests fail against gov regions

### ISSUE THREAD

**Issue by mickayz** [nccgroup/Scout2#116]
utils_s3.py assumes that the region is "us-east-1" when listing buckets, which causes a failure if the  account is only authorized for a gov region.

utils_s3.py:179
   buckets = s3_client['us-east-1'].list_buckets()['Buckets']

utils_s3.py:201
   s3_client = s3_clients['us-east-1']

**Comment by l01cd3v** [comment]
Thanks for reporting. I'll try to get a fix ASAP (though I'll need you to confirm as I do not have a gov account)

**Comment by l01cd3v** [comment]
Hi @mickayz,

I just pushed code that I think should fix the issue. Would you mind trying it and letting me know? I do not have access to a us-gov account.

Thanks

**Comment by mickayz** [comment]
Yup, just retried with the current master and it works.

One thing to note though is that if you don't provide "--regions us-gov-west-1", I think it tries every region which leads to a ton of errors for all the non-gov regions.  I wonder if adding a commandline flag like "--only-gov" might be worthwhile?

Anyways, thanks for the great software!

**Comment by l01cd3v** [comment]
Thanks for confirming ! I'll modify and rename the "--with-gov" and "--with-cn" to exclude other regions.
