### ISSUE TITLE
name 'add_sts_argument' is not defined

### ISSUE THREAD

**Issue by Flora7** [nccgroup/Scout2#120]
I suddenly got an error in old Scout2(I got it on 6 September):

```
Failed to process rule defined in iam-managed-policy-allows-sts-AssumeRole.json

Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 176, in main
    aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
KeyError: 'items'

```

So I get a new updated Scout2(get it today), but got the following error in my kali linux.

```
Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    add_sts_argument(parser, 'mfa-serial')
NameError: name 'add_sts_argument' is not defined

```

**Comment by l01cd3v** [comment]
Did you update to the latest version of opinel as well? (sudo) pip install -r requirements.txt ?

**Comment by Flora7** [comment]
Yep.
It's still have the same issues.

**Comment by l01cd3v** [comment]
I just created a new Kali Linux VM, cloned the repo, installed the requirements and was able to run the tool. Seems like something may be wrong on your system. Can you give it a try on a brand new VM?

**Comment by Flora7** [comment]
I don't have the AWS credentials anymore so cannot get the result now. Did you installed the tool in a clean kali? If yes, then the issue might be caused by some settings of my kali - I installed some other tools and therefore might effect Scout2.

**Comment by l01cd3v** [comment]
Yes, I downloaded the latest Kali Linux ISO, installed it in VMWare, cloned the repo, installed the requirements, and ran the tool successfully. I'll close this issue for now then.

**Comment by Flora7** [comment]
Okay. I'll try to run it in a new Kali in next project. Whether it works or not, I'll post the result here.
Thank you.
