### ISSUE TITLE
KeyError in get_cidr_name after switch to latest master branch

### ISSUE THREAD

**Issue by a3linux** [nccgroup/Scout2#121]
I got a KeyError in get_cidr_name in AWSScount2/utils_vpc.py line 127. 

I took a look into it and find callback_args['ip_ranges_name_key'][0] return the first character the given key name. 

I used --ip-ranges-key-name name and it is return 'n'

**Comment by l01cd3v** [comment]
I think that this should be fixed in the dev branch. Could you give it a try and confirm ?

**Comment by a3linux** [comment]
I checked the dev branch and it is the same fix I did on my local one. 
It should be work. 

Thanks.

**Comment by l01cd3v** [comment]
Merged into master, thanks !
