### ISSUE TITLE
Scout2 with SAML Authentication

### ISSUE THREAD

**Issue by sreeramsanjay** [nccgroup/Scout2#123]
Noticed that Scout2 is not working with SAML authentication and is there any way to make it work with SAML.

**Comment by l01cd3v** [comment]
There's no easy, one-fit-all way to work with SAML and the CLI, so I will not add support for this. If I had to run the tool in an environment that uses SAML auth, I'd follow a similar approach as the below blog post to get credentials saved in my ~/.aws/credentials file and be available for any tool:

https://aws.amazon.com/blogs/security/how-to-implement-a-general-solution-for-federated-apicli-access-using-saml-2-0/
