### ISSUE TITLE
Scout2 also needs user performing audit to have SNS:ListTopics now

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [nccgroup/Scout2#129]
https://github.com/nccgroup/AWS-recipes/blob/master/IAM-Policies/Scout2-Default.json policy is no more enough as described in readme. I have applied this policy to a separate aws user just to perform scout2 audits but recent changes need an update there. I wanted to check if SNS:List* is enough or more permission needs to be added ? 

An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:ap-northeast-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:ap-south-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:ca-central-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:us-east-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:sa-east-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:us-west-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:ap-northeast-2:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:us-east-2:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:eu-central-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:ap-southeast-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:us-west-2:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:ap-southeast-2:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:eu-west-1:144231315695:*
An error occurred (AuthorizationError) when calling the ListTopics operation: User: arn:aws:iam::144231315695:user/scout2 is not authorized to perform: SNS:ListTopics on resource: arn:aws:sns:eu-west-2:144231315695:*

**Comment by l01cd3v** [comment]
The policy was updated ! Thanks !
