### ISSUE TITLE
Doesn't seem to be working with GovCloud

### ISSUE THREAD

**Issue by modelenoir** [nccgroup/Scout2#131]
Love the tool and it works fine in my regular environments, all regions except GovButt.  Have you heard of this being the case or know of any reason why it wouldn't work?

I wrote my own very simple script before I found Scout2 and it's working fine now, so I'm pretty sure the keys work.  I've searched through the source and haven't found any explicit list of regions (or specific exclusion of GovButt).  Any ideas?

Anyway, thanks for the tool!  It's been great so far in the environments it's working in.

For each group I get this: An error occurred (UnrecognizedClientException) when calling the xxxxxxx operation: The security token included in the request is invalid.

**Comment by l01cd3v** [comment]
Have you tried running the tool with the "--partition-name aws-us-gov" argument? I don't have a govcloud account so cannot test but I *think* that it should work.

**Comment by modelenoir** [comment]
That was it!  Thanks a lot for the quick solution, and again the great tool!

**Comment by Bloodylegend** [comment]
In case anyone is wondering for China the syntax is: `python Scout2.py --partition-name aws-cn --force`

**Comment by modelenoir** [comment]
There is an issue using GovCloud again.  This is obviously not the way to FIX it, but it is how I embarrassingly "fixed" it.

trace:   File "/Users/xxxxxxxxxxxxx/audit/venv/lib/python2.7/site-packages/AWSScout2-3.0.5-py2.7.egg/AWSScout2/__main__.py", line 72, in main
    aws_config['aws_account_id'] = get_aws_account_id(credentials)

        # Set the account ID
        #personal hack.  except the account id error.
        try: 
            aws_config['aws_account_id'] = get_aws_account_id(credentials)
        except Exception as e:
            print "##mark debug: account issue"

**Comment by modelenoir** [comment]
Not surprisingly that did not fix the whole issue.  The report would get generated, but some services are not analyzed.
