### ISSUE TITLE
Not all RDS instances have a multi-az option

### ISSUE THREAD

**Issue by nfelsen** [nccgroup/Scout2#132]
When using [AWS Aurora](https://aws.amazon.com/rds/aurora/), in order to achieve the same result, you need to put in your Aurora cluster at least 2 instances into 2 different AZ. Currently, Scout2 mark those instances as "Single AZ RDS instance"

**Comment by l01cd3v** [comment]
Thanks ! I'll modify the rule to handle this case.

**Comment by l01cd3v** [comment]
Thanks ! Pulling the multi-az information from the cluster when necessary
