### ISSUE TITLE
DB with a retention period in days of 1 don't trigger the "Short retention period" flag

### ISSUE THREAD

**Issue by marizmendi** [nccgroup/Scout2#133]
Shouldn't it be moreThan 0, instead of 1?
https://github.com/nccgroup/Scout2/blob/master/rules/rds-instance-short-backup-retention-period.json#L6
Thanks

**Comment by l01cd3v** [comment]
Thanks ! I noticed that a little while ago and thought I pushed the fix, must have been stuck in my local dev branch.
