### ISSUE TITLE
S3 rules do not seem to be flagging "Principal": "*" ,"Action": "s3:*"

### ISSUE THREAD

**Issue by LBates2000** [nccgroup/Scout2#135]
I would think that s3-bucket-world-policy.json running with the default ruleset would flag the following as dangerous:
```
{
  "Version": "2012-10-17",
  "Id": "Policy1234567890123",
  "Statement": [
    {
      "Sid": "Stmt1234567890123",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::some-bucket-here",
        "arn:aws:s3:::some-bucket-here/*"
      ]
    }
```
It does not seem to do so though, and I've been unable to create a rule that will trigger this as dangerous.

**Comment by l01cd3v** [comment]
Thanks, I've noticed this issue as well. I'll look into it.

**Comment by l01cd3v** [comment]
This is fixed in the dev branch, will close once I merge
