### ISSUE TITLE
AuthorizationError with severals accounts

### ISSUE THREAD

**Issue by steve-heslouin** [nccgroup/Scout2#136]
First of all, thanks for your project, sounds really promising. 
Nevertheless for me, it doesn't work, our company is organised in a way that everyone connect to the main account on which there is no resources at all (all operation get denied by default), its just used as a gateway to switch between accounts. (its AWS best practise when an Organisation has severals accounts).

With boto3, its work fine and i do it as follow.

```
cat ~/.aws/credentials
[account1]
aws_access_key_id = ...
aws_secret_access_key = ..
region=us-east-1
role_arn=arn:aws:iam::...

[account2]
aws_access_key_id = ...
aws_secret_access_key = ..
region=us-east-1
role_arn=arn:aws:iam::...
```
example working boto3 starter for s3
```
import boto3

client = boto3.Session()
profiles = client.available_profiles <= return ["account1","account2"]
boto3.setup_default_session(profile_name='account1')
s3 = boto3.resource('s3')
for bucket in s3.buckets.all():
...     print bucket.name
bucket1
bucket2
etc...
```

This snippet works fine and i successfully retrieve any kind of informations from "account1" or "account2"

So with your program, i tried the following command line, for example s3

```
python Scout2.py --profile account1 --services s3
```
and it returns me for every single operation

```
Error: could not fetch s3 configuration.
An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
```

While i do have all perms since i succesfully retrieve them using boto3 lib. So i'am unsure where is the problem, but i would love to be able to try your program, may be could be a quick fix ? In anycase, if you think its a bug, i can help you out with it for testing. 

Regards

Steve

**Comment by l01cd3v** [comment]
Hi,

Thanks for reporting the issue. I have a question about your configuration. In your "account1" and "account2" profiles, I am assuming the access key ID and secret key are the same, and actually correspond to an IAM user in something we could refer to as "account0" (the account with no resources)?

If that's the case, I didn't know that this is a valid way to configure accounts and I'll try to think of a way to support it (not sure I'll be able to in the short term). However, meanwhile, the tool should work if you modify your configuration as follow:

[account0]
aws_access_key_id = ...
aws_secret_access_key = ..

[profile account1]
source_profile = account0
region=us-east-1
role_arn=arn:aws:iam::...

[profile account2]
source_profile = account0
region=us-east-1
role_arn=arn:aws:iam::...

Please let me know if this works or if I missed something.

**Comment by steve-heslouin** [comment]
Hi, 

```
 I am assuming the access key ID and secret key are the same, and actually correspond to an IAM user in something we could refer to as "account0" (the account with no resources)?
```
Exactly !

Actually, my original config file looked like this at the beginning
```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[account0]
region=us-east-1
role_arn=arn:aws:iam::...
source_profile=default

[account1]
region=us-east-1
role_arn=arn:aws:iam::...
source_profile=default
```
But with this config, it didn't worked at all

```
python Scout2.py --profile codewise-office --services ec2
Error: could not find AWS credentials. Use the --help option for more information.
```

So my guess is that the program wasn't parsing correctly the credentials file, so that why i modified my credentials file the way i show in the first post, otherwise, no joy.

Thanks for your support :)

**Comment by l01cd3v** [comment]
I think that you need the "profile" keyword in front of account1 and account2, which may be my mistake in forcing it while it's not necessary? Can you give it a try?

[default]
[profile account1]
[profile account2]

**Comment by steve-heslouin** [comment]
My new ~/.aws/credentials with profile
```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[profile account1]
region=us-east-1
role_arn=arn:aws:iam::...
source_profile=default

[profile account2]
region=us-east-1
role_arn=arn:aws:iam::...
source_profile=default
```
But same error message

```
python Scout2.py --profile account1 --services ec2
Error: could not find AWS credentials. Use the --help option for more information.
```

**Comment by l01cd3v** [comment]
Ok, I'll try to repro to figure out what's wrong. It should be working...

**Comment by steve-heslouin** [comment]
If it help, my "account0" is called a cross account access, notice the config file with **account0-cross-account-access**

In the credentials file, replacing the ... with a little bit more verbose look like this


```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[account1]
region=us-east-1
role_arn=arn:aws:iam::XXXXXXXXXXXX:role/account0-cross-account-access
source_profile=default

[account2]
region=us-east-1
role_arn=arn:aws:iam:YYYYYYYYYYYYYYY:role/account0-cross-account-access
source_profile=default

[account3]
region=us-east-1
role_arn=arn:aws:iam::ZZZZZZZZZZZZZZZ:role/account0-cross-account-access
source_profile=default
```

I keep at your entire dispostion if you need some tests ;)

Thanks

Steve

**Comment by l01cd3v** [comment]
The issue was I was only looking for profiles with a role_arn and source profile in the ~/.aws/config file, not in the ~/.aws/credentials file.

I've pushed a fix and will merge the PR as soon as Travis' build completes

**Comment by l01cd3v** [comment]
Should be fixed now, Please do a git pull and pip install -r requirements.txt as the fix is in the underlying opinel module.

**Comment by steve-heslouin** [comment]
HI @l01cd3v 

Thanks a tons for your reactivity, much appreciated!

Since Im using docker, it directly created new instance with a new clone of your repo

my credentials file look as follow now:
```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[account1]
region=us-east-1
role_arn=arn:aws:iam::XXXXXXXXXXXX:role/account0-cross-account-access
source_profile=default

[account2]
region=us-east-1
role_arn=arn:aws:iam::YYYYYYYYYYYYYY:role/account0-cross-account-access
source_profile=default

[account3]
region=us-east-1
role_arn=arn:aws:iam::ZZZZZZZZZZZZZ:role/account0-cross-account-access
source_profile=default
```
But when i run as follow, i got the following error
```
python Scout2.py --profile account1 --services ec2
Traceback (most recent call last):
  File "Scout2.py", line 322, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 72, in main
    credentials = read_creds(args.profile[0], args.csv_credentials, args.mfa_serial, args.mfa_code)
  File "/usr/local/lib/python2.7/dist-packages/opinel/utils.py", line 548, in read_creds
    credentials = assume_role(profile_name, credentials, role_arn, role_session_name)
  File "/usr/local/lib/python2.7/dist-packages/opinel/utils.py", line 461, in assume_role
    with open(cached_credentials_filename, 'wt+') as f:
IOError: [Errno 2] No such file or directory: '/root/.aws/cli/cache/account1--arn_aws_iam__XXXXXXXXXX_role-account0-cross-account-access.json'
```
Do you have any ideas?

Thanks again.

Steve

**Comment by l01cd3v** [comment]
Yes, the folder ~/.aws/cli/cache does not exist. Pushing a fix now

**Comment by l01cd3v** [comment]
Ok, can you give it another try?

**Comment by steve-heslouin** [comment]
You are awesome !!

It worked just great

```
python Scout2.py --profile account1 --services s3
Fetching S3 buckets config...
46/215Failed to get config for perf-test-reference-data
An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
214/215
Analyzing VPC config...
Parsing EC2 instances...
Parsing ELBs...
Parsing Redshift clusters...
Parsing RDS instances...
Analyzing AWS config...
Saving config...
Saving config...
Creating report-account1.html ...
```

As its getting late european eastern time, i will not try in deep tonight, but first hour tomorrow morning, i'm on it and will deeply test your program.

Thanks a ton for your amazing support, let me work with it some time and if i got some valuable feedback, i'll definitely write you something ;)

Kind Regards

An happy security engineer :)
