### ISSUE TITLE
"could not fetch iam configuration. expected a string or other character buffer object"

### ISSUE THREAD

**Issue by d-j-c** [nccgroup/Scout2#138]
I am getting this error when I run scout - have tried with the AWS readOnlyAccess managed policy and also the Scout2 Default AWS Recipe policy.  The report seems to be ok?

Also note the 'dictionary changed size' among the EC2 and VPC config table.

commit 33ad8e91e66c3de4295d69b837c631d8ab6da420

```
$ ./Scout2.py 
Fetching RDS config...
Fetching IAM config...
 Users: 13/13
 Groups: 2/2
 Roles: 17/17
 Managed_Policies: 14/14
 Credential report: 1/1
 Password policy: 1/1
Error: could not fetch iam configuration.
expected a string or other character buffer object
Fetching CloudTrail config...
Fetching SNS config...
          Topics   Subscriptions
             2/2             2/2
Fetching S3 buckets config...
6/6
Fetching basic VPC information...
Fetching EC2 and VPC config...
              region   Elastic IPs   Elastic LBs     Flow Logs     Instances  Network ACLs   Sec. Groups       Subnets
      ap-northeast-1           0/0           0/0             0           0/0             0           1/1             0
      ap-northeast-2           0/0           0/0             0           0/0             0           1/1             0
          ap-south-1           0/0           0/0             0           0/0             0           1/1             0
      ap-southeast-1           0/0           0/0             0           0/0             0           1/1             0dictionary changed size during iteration
      ap-southeast-1           0/0           0/0             0           0/0             0           1/1             0
      ap-southeast-2           5/5           0/3             2         23/23             0         51/51             0
        ca-central-1           0/0           0/0             0           0/0             0           1/1             0
        eu-central-1           0/0           0/0             0           0/0             0           1/1             0
           eu-west-1           0/0           0/0             0           0/0             0           1/1             0
           eu-west-2           0/0           0/0             0           0/0             0           1/1             0
           sa-east-1           0/0           0/0             0           0/0             0           1/1             0
           us-east-1           0/0           0/0             0           0/0             0           1/1             0
           us-east-2           0/0           0/0             0           0/0             0           1/1             0
           us-west-1           0/0           0/0             0           0/0             0           1/1             0
           us-west-2           0/0           0/0             0           0/0             0           1/1             0
Fetching Redshift config...
Analyzing VPC config...
Parsing EC2 instances...
Parsing ELBs...
Parsing Redshift clusters...
Parsing RDS instances...
Analyzing EC2 config... Success
Analyzing AWS config...
Saving config...
```

**Comment by l01cd3v** [comment]
Would you mind checking if the dev branch has the same issue? If it does, could you share the output using the --debug argument?

Thanks

**Comment by d-j-c** [comment]
I don't see this in the dev branch. 

Do you recommend running from the dev branch presently? Looks like some good improvements here - I like the service categorisations based on the categories used by AWS. Although I do use the `--ip-ranges` switch extensiveley which doesn't look like it's in there yet.

I also have a few ideas for contributions - if I get the time to work on these would the dev branch be the place to work from?

**Comment by l01cd3v** [comment]
Thanks for confirming it's gone w/ the dev branch.

Indeed the ip-ranges functionality is the major missing feature on dev, I hope to get it done by the end of the week. I'm at a point where I need to have the dev branch tested so feel free to file issues if you see anything wrong with it.

I'd definitely recommend working off the dev branch if you're looking to do some code changes / PR due to the major code changes that have happened. Otherwise feel free to use either branch. Master is what you're used to and you won't have any surprises, dev brings more value but may be less stable. I hope to merge dev pretty soon though.

**Comment by d-j-c** [comment]
FYI I noticed some commits on the ip-ranges functionality in dev branch so tried it out. When I ran it I saw the report-generation run through twice, and no CIDRs labelled in the report. I figure this is not complete but thought it may be useful to you.

```
Fetching SNS config...
            Regions             topics      subscriptions
              14/14                0/0                0/0
Saving data to scout2-report/inc-awsconfig/aws_config.js
Saving config...
File 'scout2-report/inc-awsconfig/aws_config.js' already exists. Do you want to overwrite it (y/n)? y
Saving data to scout2-report/inc-awsconfig/exceptions.js
Saving config...
File 'scout2-report/inc-awsconfig/exceptions.js' already exists. Do you want to overwrite it (y/n)? y
Creating scout2-report/report.html ...
File 'scout2-report/report.html' already exists. Do you want to overwrite it (y/n)? y
Matching EC2 instances and IAM roles...
Analyzing AWS config...
Analyzing AWS config...
Saving data to scout2-report/inc-awsconfig/aws_config.js
Saving config...
File 'scout2-report/inc-awsconfig/aws_config.js' already exists. Do you want to overwrite it (y/n)? y
Saving data to scout2-report/inc-awsconfig/exceptions.js
Saving config...
File 'scout2-report/inc-awsconfig/exceptions.js' already exists. Do you want to overwrite it (y/n)? y
Creating scout2-report/report.html ...
File 'scout2-report/report.html' already exists. Do you want to overwrite it (y/n)? y
(venv)
```

**Comment by l01cd3v** [comment]
The IP ranges should be fixed, one thing to note is that I changed the name of the argument that specifies the name of the attribute holding the CIDRs name from "ip-ranges-key-name" to "ip-ranges-name-key".

My tests show that the following command adds the name:

./Scout2.py --ip-ranges ip-ranges-scout2.json --ip-ranges-name-key name --force

I'm wondering if this argument used to to default to something and no longer does.... can you share the command line you used to test this? If there was a default value I should probably restore it.

**Comment by l01cd3v** [comment]
As far as the double write thing, this is a known issue due to the fact I use classes to store each service's config now but I still need a dictionary for the analysis. Working on a fix now.

**Comment by l01cd3v** [comment]
The double write should be taken care of now

**Comment by d-j-c** [comment]
Thanks for the updates, pretty hectic this week so will get back into it after the easter break :)

**Comment by l01cd3v** [comment]
Sounds good, thanks !
