### ISSUE TITLE
When using the new --timestamp option, the names of files in the 'scout2-report/inc-awsconfig/' directory contain the timestamp twice.

### ISSUE THREAD

**Issue by grettir** [nccgroup/Scout2#143]
When using the `--timestamp` option, the names of files in the `scout2-report/inc-awsconfig/` directory contain the timestamp twice.

For example, the HTML source may be trying to load the following JavaScript files:

```html
<script src="inc-awsconfig/aws_config-xxxxxxxx-2017-04-24_11h58-0600.js"></script>
<script src="inc-awsconfig/exceptions-xxxxxxxx-2017-04-24_11h58-0600.js"></script>
```

But the actual files generated by Scout2 have the following filenames:

```
inc-awsconfig/aws_config-xxxxxxxx-2017-04-24_11h58-0600-2017-04-24_11h58-0600.js
inc-awsconfig/exceptions-xxxxxxxx-2017-04-24_11h58-0600-2017-04-24_11h58-0600.js
```

**Comment by l01cd3v** [comment]
Thanks for reporting, should be fixed !
