### ISSUE TITLE
Typo in AWSScout2/output/data/html/partials/services.vpc.regions.id.vpcs.html

### ISSUE THREAD

**Issue by tensult** [nccgroup/Scout2#149]
Current: var single_vpc_template = Handlebars.compile($("#single__vpc-template").html());
Should be: var single_vpc_template = Handlebars.compile($("#single_vpc-template").html());

Fixed in my forked repo:
https://github.com/tensult/Scout2/commit/c9120e674ebdaeb594fc0a1c8dddcb3788071df4

**Comment by l01cd3v** [comment]
Thanks ! Created and merged a PR.
