### ISSUE TITLE
Getting Segmentation fault when Fetching VPC config

### ISSUE THREAD

**Issue by prasadpucsdian** [nccgroup/Scout2#154]
Hi Team,

When I am trying to get data getting "Segmentation fault" after Fetching VPC config or get "Killed" Fetching VPC config

I am using below command.
Scout2  --profile "Profile_Name"  --report-dir /var/www/html/scout2-report/ --no-browser --update

NOTE:- I am not using username I have created on role (as per doc mention here)and that role is assigned to instance on which I have installed Scout2.

**Comment by l01cd3v** [comment]
Hi,

May you please specify the following so that I can try to repro:
- instance type
- OS version
- Scout2 version

Thanks

**Comment by prasadpucsdian** [comment]
Hi Please find below instance.
instance type - t2.micro
OS version - ubuntu-trusty-14.04-amd64-server-20170405 
Scout2 version - I am not able to find version. (I install Scount2 today 5 Jun 2017)

Below is the exact error which I observed 1st time.
Fetching VPC config...
             regions               vpcs          flow_logs       network_acls       route_tables            subnets
Error: could not fetch vpc configuration.
can't start new thread
Fetching EMR config...
             regions           clusters
Error: could not fetch emr configuration.
can't start new thread
Fetching ElastiCache config...
             regions           clusters    security_groups
Segmentation fault

**Comment by l01cd3v** [comment]
Thanks, this is due to limited resources on the instance. I thought this was fixed when I modified the threading strategy but apparently not. I'll see if I can repro & fix.

Meanwhile, If you are in a rush, run Scout2 on a larger instance and you shouldn't see this error.

**Comment by prasadpucsdian** [comment]
Hi,

Thanks for your assistance. 
The issue is resolved now. I have changed my instance type to t2.medium.

**Comment by renutz** [comment]
Em terça-feira, 6 de junho de 2017, prasadpucsdian <notifications@github.com>
escreveu:
