### ISSUE TITLE
date first spotted

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#155]
it would be great to have a finding for when it was first spotted.

**Comment by l01cd3v** [comment]
What do you mean?

**Comment by jjegg** [comment]
Basically, I plan on running your framework on a cronjob say daily or weekly. It would be great to have the ability to identify what has changed or what is new from the last report or last scan. Maybe we could then trigger an alert framework based off this.

**Comment by l01cd3v** [comment]
This feature won't be added in the foreseeable future. Scout2 is designed to provide details at a point in time. If you want continuous monitoring and differential analysis, look into:
- https://github.com/Netflix/security_monkey
- Leveraging AWS config in your own way
