### ISSUE TITLE
s3 domain generates red when only yellow findings

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#156]
When running this framework on my account, it generated a red finding when there were only three yellow findings. What is the logic behind this?

**Comment by l01cd3v** [comment]
No logic, just a bug

**Comment by l01cd3v** [comment]
I can repro it, will look into it

**Comment by jjegg** [comment]
Awesome!!

**Comment by l01cd3v** [comment]
Should be fixed - Closing
