### ISSUE TITLE
Mark findings as false positive

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#157]
As mentioned before it would be great to have state somehow and the ability to mark findings as false positive or down rank them via html.

**Comment by l01cd3v** [comment]
Yes, this is something I plan on working on when I get time

**Comment by l01cd3v** [comment]
This has been implemented on the dev branch - The workflow is as follow:

1. View issues 
2. Browse to the false positive item
3. Click on it (colored text / badge)
4. Confirm a popup is displayed, select "ok" to confirm
5. Click on the top-right "Help" menu and select "Export exceptions"
6. Re-run with the following arguments " --local --exceptions <path-to-downloaded-file>

**Comment by l01cd3v** [comment]
The dev branch has been merged w/ master now, closing.
