### ISSUE TITLE
An error occurred (Throttling)

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#163]
How does this framework deal with throttling for api calls? if this an issue? Will it not retreive information? 

An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded
An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded
An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded
An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded
An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded

**Comment by l01cd3v** [comment]
It currently doesn't handle well AWS's throttling of API calls. Try the following:

./Scout2.py --update --services cloudformation

The error may still happen though as throttling is service-specific (depends if you triggered it by making multiple runs within a short amount of time or if a single run triggered this). I used to support resumption (in IAM only) with the --resume argument, but I haven't re-implemented this with the new threading code.
