### ISSUE TITLE
Ruleset level: Informational

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#164]
Feature request for having the ability to mark a rule as Informational, Warning or Danger. For example, I don't think that having an S3 bucket as a public website should be a warning, but instead maybe just informational?

**Comment by l01cd3v** [comment]
I thought I disabled that rule in the default ruleset. I see two options here:
- add an informational level of warning
- use this rule as a filter for S3 buckets rather than a finding

I _think_ that I may go for the informational finding level, but let me think about this for a little bit.

**Comment by l01cd3v** [comment]
So went the second way for now, made this rule a filter as this is not a security finding (does not affect ACLs / permissions on objects in bucket).
