### ISSUE TITLE
Doesnt work on a Mac

### ISSUE THREAD

**Issue by TimGurney** [nccgroup/Scout2#167]
Opening the HTML report...
0:60: execution error: "file:///Users/wolf/scout2-report/report.html" doesn’t understand the “open location” message. (-1708)
70:78: execution error: Can’t get application "firefox". (-1728)

It makes assumptions about the browser that is available.

**Comment by l01cd3v** [comment]
I'll have to follow up w/ some coworkers as I do not have a Mac for testing, though I'm pretty sure that I've seen Scout2 work on OS X before. Scout2 itself does not make any assumptions about the available browser, I use the Python webbrowser module (https://docs.python.org/2/library/webbrowser.html).

I tested on Windows w/ chrome & edge setup as the default browser and it works fine, so I _think_ it may be a configuration issue on your end but I will double check if anyone I know as seen this issue / knows how to fix it.

In the meantime, feel free to use the --no-browser argument and open the file at `scout2-report/report(-profile_name).html` in your favorite browser.

**Comment by l01cd3v** [comment]
I just heard confirmation that the latest code runs fine on OS X. 

Someone suggested you may have installed Firefox a while ago, associated it w/ HTML files, and uninstalled it. Try setting your favorite browser as the default app when opening HTML files and see if this fixes the issue?

**Comment by l01cd3v** [comment]
To test this (after setting a new default app for opening HTML files), you don't need to fetch the new config:

./Scout2.py --local

**Comment by timgurney-ee** [comment]
Hi

Never installed firefox this is a brand new MBP

**Comment by timgurney-ee** [comment]
I opened up finder and then located the report and double clicked it and it open (as expected) in safari.

**Comment by l01cd3v** [comment]
Weird... would you mind trying the following patch and let me know if this catches the exception? I can't / don't have time to look into this but I can push a fix like this to handle the error if it works:

diff --git a/AWSScout2/__main__.py b/AWSScout2/__main__.py
index 12d22a0..bfd4c76 100644
--- a/AWSScout2/__main__.py
+++ b/AWSScout2/__main__.py
@@ -107,5 +107,8 @@ def main():
     if not args.no_browser:
         printInfo('Opening the HTML report...')
         url = 'file://%s' % os.path.abspath(html_report_path)
-        webbrowser.open(url, new=2)
+        try:
+            webbrowser.open(url, new=2)
+        except:
+            printError('Error - Please manually open the file at %s' % url)

**Comment by timgurney-ee** [comment]
Hi

no problem I will push that in later and let you know. 

btw I also check my default browser config (general setting in macos) and it is set to Safari - I havent used FF for years to be honest, either Safari or Chrome.

**Comment by l01cd3v** [comment]
There's no mention of firefox anywhere in the code base for Scout2, this must be a bug in the Python webbrowser module. Maybe this could be reported later if we find a way to repro: could you share the version of python & OS X you're using?

**Comment by l01cd3v** [comment]
You'll actually need to import printError to try that attempted fix; proper git diff:

```
diff --git a/AWSScout2/__main__.py b/AWSScout2/__main__.py
index 12d22a0..92d51d5 100644
--- a/AWSScout2/__main__.py
+++ b/AWSScout2/__main__.py
@@ -8,7 +8,7 @@ import webbrowser
 
 try:
     from opinel.utils.aws import get_aws_account_id
-    from opinel.utils.console import configPrintException, printInfo
+    from opinel.utils.console import configPrintException, printInfo, printError
     from opinel.utils.credentials import read_creds
     from opinel.utils.globals import check_requirements
 except Exception as e:
@@ -107,5 +107,9 @@ def main():
     if not args.no_browser:
         printInfo('Opening the HTML report...')
         url = 'file://%s' % os.path.abspath(html_report_path)
-        webbrowser.open(url, new=2)
+        try:
+            webbrowser.open(url, new=2)
+        except:
+            printError('Error - Please manually open the file at %s' % url)
```

**Comment by timgurney-ee** [comment]
Running the latest OSX - I always install the latest versions when available, as for python: 2.7.12

**Comment by l01cd3v** [comment]
Thanks, I'll try to see if it's a python 2.7.12 thing

**Comment by nycnewman** [comment]
Looks like a 10.12.5 specific issue that should get fixed in 10.12.6. See: https://bugs.python.org/issue30392

**Comment by timgurney-ee** [comment]
ah right nice one well spotted.

**Comment by l01cd3v** [comment]
Thanks for pointing that out ! Closing this issue for now.

**Comment by l01cd3v** [comment]
@TimGurney , did catching the exception work? If so I may just push this patch just in case
