### ISSUE TITLE
Route53 Domain Transfer Flagged for .io

### ISSUE THREAD

**Issue by ddilts** [nccgroup/Scout2#170]
Route53 doesn't allow transfer locks on .io domains. Is there a way to not flag this as red?

**Comment by l01cd3v** [comment]
Thanks for letting me know, I didn't know that! After some more reading, it appears that .io does not support domain lock, this is not a Route53 thing. Neither do .CO.NZ domains apparently (https://support.google.com/domains/answer/3290306?hl=en).

Although domain lock is not supported, the risk remains valid. The question then is whether you accept it or not. In this case, the best approach is to use a custom ruleset. I will be working on the ruleset generator to fix issue #169 soon.

I'll further think about it, but my initial idea is as follow:
- Modify the existing rule to ignore .io and .co.nz domains
- Create a new rule that flags (still in red) use of .io and .co.nz domains with the rationale given above.

In this case, your solution would be to use a custom ruleset that has disabled the new rule.

**Comment by l01cd3v** [comment]
Implemented what I proposed earlier.
