### ISSUE TITLE
Couple of minor bugs and VPC NACL issues

### ISSUE THREAD

**Issue by nycnewman** [nccgroup/Scout2#171]
Found two bugs in VPC code.

- line 151 & 156 - both need Vpn not Vpc
- Under VPCConfig - agteway instead of gateway

Also (but haven't been able to work out fix) the VPC checks for default NACLs appear to be broken as it continues to report on these despite implementing non-default NACLs in each region. If you change default NACL to block all traffic these are also still called out as open.

**Comment by nycnewman** [comment]
Pull request #172 added to fix issues. VPC NACL checks outstanding

**Comment by nycnewman** [comment]
PR #172 updated to fix logic around VPC and identification of default subnets and NACLs that are open for ingress/egress

**Comment by l01cd3v** [comment]
X-post in PR as well - Ok, so I pushed a number of changes to fix the issue related to processing the rules. This means the previous rules are "gone" and replaced with the following set:

- "Network ACLs allow all ingress/egress traffic (custom/default)", which means 4 rules with the following:
  - ingress/egress is the direction
  - default meaning that these are NACLs as created by default by AWS (2 rules, 100 allow all, 32565 deny all)
  - custom meaning any NACL that does not match the default AWS rules

The distinction between custom and default is helpful to determine whether an attempt at creating NACLs was made (and errors occured) or whether the default behavior was left as is.

- "Unused network ACL": when a NACL that is not the default for the VPC is not attached to any subnet

- "Subnet with allow all ingress/egress NACLs": somewhat redundant w/ the first set of rules, but highlights subnets to which bad NACLs have been applied to.
