### ISSUE TITLE
Credentials not found when using Temporary Credentials 

### ISSUE THREAD

**Issue by juanantoniofm12** [nccgroup/Scout2#177]
Hi:

We are using [Temporary credentials](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html) to manage access to our AWS resources. And we use profiles, as we have multiple accounts.

When trying to use Scout2, it fails to find suitable credentials. I took a look at opinel, and it seems to be looking for 2 profiles "my-aws-profile" and "my-aws-profile-nomfa". So I also tried authenticating on the cli(using my normal way of doing so), and copying the creds to a profile "my-aws-profile-nomfa" just to try. BotoCore still complains that is an invalid token:

    botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetSessionToken operation: The security token included in the request is invalid.

but using the aws cli with that same token, works. And our custom scripts, written with boto3 and botocore, also work.

Is there any way of using Scout2 with temporary security credentials?

Thanks. Sorry for the long post, here is a potato: 🥔

**Comment by jsimoni** [comment]
I also have this problem with [Assuming a Role and Using MFA](http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html#cli-roles-mfa).

**Comment by l01cd3v** [comment]
I have been using temporary credentials for a while with no issues, can you share more details about your setup? OS version ? Python version ? how do you configure the credentials ?

**Comment by sh1n0b1** [comment]
I'm running into the exact same issue too.

**Comment by l01cd3v** [comment]
I need more information than that to repro / troubleshoot. Can you share your OS version ? Python version ? how do you configure the credentials ?

**Comment by l01cd3v** [comment]
ping @sh1n0b1 @jsimoni @juanantoniofm12 - more info ?

**Comment by pwes019** [comment]
I'm having a similar problem.  In the environment I'm testing, there are no IAM users.  The console is accessed using SAML-based federated authentication.  So the only way to get API access is by generating Temporary Credentials.  When I try this I get: "Error: could not find AWS credentials. Use the --help option for more information.".  I've tried loading the credentials in the credentials file a separate profile, in the default profile and from a csv file. 
Running: 
* Linux kali2 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux
* Python 2.7.13

**Comment by l01cd3v** [comment]
Could you let me know how you configured the credentials in a separate (or the default) profile? and did you confirm that the CLI was working with this setup?

**Comment by pwes019** [comment]
I've followed [these instructions](https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/) to issue temporary credentials.  At the end of this script is a simple API example to list s3 buckets.  This does list the s3 buckets, so the CLI is working. The script adds a [saml] profile to your aws credentials file - which should then just work - so you don't have to manually update it.  To confirm the profile is working I simply tried: aws s3 ls --profile saml
which provided a bucket listing as expected.

I did update the default profile manually temporarily just to see if the credentials would work when added there.  My credentials file looks like this with two separate key pairs - default for another instance and saml:

root@kali2:~/.aws# cat credentials
[default]
aws_access_key_id = ********************
aws_secret_access_key = *********************************

[saml]
output = json
region = ap-southeast-2
aws_access_key_id = ********************
aws_secret_access_key = *********************************
aws_session_token = *********************************

**Comment by l01cd3v** [comment]
Can you try updating opinel to version 3.1.3 (just published a minute ago) and let me know if this solves the problem?

If not, please run with --debug and share the log.

**Comment by pwes019** [comment]
Trace is now working.  It was a policy error.  I'll look into sorting this out at my end. "ClientError: An error occurred (AccessDenied) when calling the ListPolicies operation: User: arn:aws:sts::************:assumed-role/AWS-Admins/********@*******.**.** is not authorized to perform: iam:ListPolicies on resource: policy path /"

**Comment by pwes019** [comment]
Now working fine for me once I sorted out permissions.  Thanks

**Comment by l01cd3v** [comment]
Thanks. I'll leave this open for a little longer then close it unless I hear otherwise
