### ISSUE TITLE
Need to handle rate limiting

### ISSUE THREAD

**Issue by Ashex** [nccgroup/Scout2#178]
Presently there doesn't appear to be any sort of backoff configured when the rate limit is exceeded, as a result when there's a large number of resources found Scout2 will quickly hit it resulting in the console being filled wth error messages:

Errors I've encountered:
```
An error occurred (Throttling) when calling the ListIdentityPolicies operation (reached max retries: 4): Rate exceeded
An error occurred (Throttling) when calling the GetStackPolicy operation (reached max retries: 4): Rate exceeded
An error occurred (RequestLimitExceeded) when calling the DescribeSnapshotAttribute operation (reached max retries: 4): Request limit exceeded.
```

**Comment by kevinqiu92** [comment]
I've noticed this too. I tried playing around with the threading and it wasn't particularly easy to find a parameter that helps reduce this.

**Comment by kevinqiu92** [comment]
actually @Ashex i found that by decreasing the threads specified in the `init_threading` calls the scans were a lot slower but didn't seem to hit the rate limit

**Comment by l01cd3v** [comment]
This should have been fixed on the dev branch, will be merged in master soon
