### ISSUE TITLE
Rules with olderThan and newerThan comparisons are failing

### ISSUE THREAD

**Issue by petergoldstein** [nccgroup/Scout2#180]
When I run Scout2 (Mac OSX, installed with pip) I'm getting some rule failures:

Failed to process rule defined in iam-root-account-used-recently.json
'<' not supported between instances of 'int' and 'str'
Failed to process rule defined in iam-user-no-Active-key-rotation.json
'>' not supported between instances of 'int' and 'str'
Failed to process rule defined in iam-user-no-Inactive-key-rotation.json
'>' not supported between instances of 'int' and 'str'

The failing rules all appear to be related to date comparisons.

Looking at the Opinel codebase, it looks like the expected argument to the 'olderThan' and 'newerThan' operators should be an array of two elements - an integer and a units as a string.  For example, [90, "days"].

But in these JSON files, the argument being passed into the operators is a [string, string].  In one case the array is ["90", "days"].  And in the other the argument is ["_ARG_1_", "days"].  I'm not sure how to format the JSON in the latter case so the value is converted to an integer, or I would submit a PR.

**Comment by l01cd3v** [comment]
Thanks for reporting. I cannot repro in my linux env and do not have OSX available, but I modified opinel to do a typecast - hopefully this resolves the issue: get the latest version of Scout2 and install the requirements (latest version of opinel).

**Comment by l01cd3v** [comment]
Closing for now, please reopen if this did not help
