### ISSUE TITLE
Rule for expired testing and staging services

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#183]
If an instance has been living for over 3 months with testing or staging tag with a public IP or EIP attached, an information flag should be shown

**Comment by l01cd3v** [comment]
This rule is too specific to your environment to make it to the default ruleset, but feel free to submit a parameterized rule (based on existing rules @ https://github.com/nccgroup/Scout2/tree/master/AWSScout2/rules/data/findings, I haven't had time to create a tutorial / document for how to create new rules).

This way, you'll get to only need to maintain your custom ruleset that specifies the parameterized rule name, along with the parameters (in this case age > 3 months, tag[name] = testing or staging.

**Comment by l01cd3v** [comment]
Marking as wontfix for now but leaving open for PR

**Comment by l01cd3v** [comment]
I pushed a couple of rules that may help in creating this type of rule - closing
