### ISSUE TITLE
Filtering of results

### ISSUE THREAD

**Issue by unk1nd0n3** [nccgroup/Scout2#188]
Hi,

thank for great tool. May I ask you to add next filters to reports:

1. All High findings
2. All Medium finding

Thanks

**Comment by l01cd3v** [comment]
Hello,

I'm not sure what you mean by that - how / where would these filter be used?

**Comment by SrebniukNik** [comment]
Hi,
this is kind of filters: Role for EC2, Role for Lambda, etc and result be:

1. All critical non compliant findings
2. All medium non compliant findings

**Comment by l01cd3v** [comment]
I see, will look into this.

**Comment by j4v** [comment]
Closed as this is implemented in https://github.com/nccgroup/ScoutSuite/i. Considered `wontfix` for Scout2.
