### ISSUE TITLE
Producing reports that can be served successfully from Jenkins "userContent"?

### ISSUE THREAD

**Issue by cotman** [nccgroup/Scout2#190]
Possibly just our own ignorance here, but...

We're finding the Scout2 report massively useful, especially for weeding out issues with our security groups.

However, it's so useful that we'd like to run it in a weekly scheduled Jenkins job and have the output generated into Jenkins [userContent](https://wiki.jenkins.io/display/JENKINS/User+Content) so the reports can be viewed easily.

The problem is that the generated report doesn't work when we do this - the same report files *will* work if downloaded locally and launched in the "normal" way.  General consensus seems to be that there's an issue precompiling the handlebars templates when it sits within Jenkins userContent.

Is there a relatively straighforward way to do what we're trying to do with Scout2, as it stands?

Thanks.

**Comment by l01cd3v** [comment]
I've never tried to host files on Jenkins like that, have you looked at the web console when browsing to it? Maybe importing some of the JS dependencies fails and subsequently results in the templates not being compiled.
