### ISSUE TITLE
VPC Network ACL Error

### ISSUE THREAD

**Issue by nic1390** [nccgroup/Scout2#192]
I am getting this error when running

Processing CloudTrail config...
Analyzing VPC Network ACLs...
'>' not supported between instances of 'str' and 'int'
Path: ['regions', 'ap-northeast-1', 'vpcs', 'vpc-01f10464', 'network_acls']
Key = network_acls
Value = acl-145fab71
Path = []
'>' not supported between instances of 'str' and 'int'
Path: ['regions', 'ap-northeast-2', 'vpcs', 'vpc-e9a74680', 'network_acls']
Key = network_acls
Value = acl-25ef0e4c
Path = []
'>' not supported between instances of 'str' and 'int'
Path: ['regions', 'ap-south-1', 'vpcs', 'vpc-408e6d29', 'network_acls']

**Comment by nic1390** [comment]
Also getting this

unable to process testcase 'inSubnets' on value '0.0.0.0/0', interpreted as False.
Current path: ['vpc', 'regions', 'ap-northeast-1', 'vpcs', 'vpc-01f10464', 'network_acls', 'acl-145fab71']
'use_default_ingress_rules'
Current path: ['vpc', 'regions', 'ap-northeast-1', 'vpcs', 'vpc-01f10464', 'network_acls', 'acl-145fab71']


Failed to process rule defined in vpc-default-network-acls-allow-all.json
Current path: ['vpc', 'regions', 'ap-northeast-1', 'vpcs', 'vpc-01f10464', 'network_acls', 'acl-145fab71']
'use_default_egress_rules'
Current path: ['vpc', 'regions', 'ap-northeast-1', 'vpcs', 'vpc-01f10464', 'network_acls', 'acl-145fab71']

**Comment by l01cd3v** [comment]
I _think_ that I just fixed it on the dev branch - Feel free to give it a try and let me know. Thanks

**Comment by l01cd3v** [comment]
I merged dev w/ master and released a new package as well (v 3.0.5)
