### ISSUE TITLE
Error Scout2RuleGenerator JavaScript

### ISSUE THREAD

**Issue by i4specete** [nccgroup/Scout2#199]
Hi,

when I try to create new ruleset with your extesion Scout2RuleGenerator, the js throw the following error:

TypeError: aws_info.rule_definitions[rule_filename].arg_names is undefined

Do I have to create the project in some specific path?

Thanks a lot!!

**Comment by i4specete** [comment]
Don't appears any rules to modify  when I execute Scout2RulesGenerator --ruleset-name demo

**Comment by l01cd3v** [comment]
Thanks, i'll look into it

**Comment by i4specete** [comment]
Could you check this?

**Comment by l01cd3v** [comment]
Sorry - I fixed the issue on the dev branch. I will merge the code in master soon.

**Comment by l01cd3v** [comment]
Merged w/ master
