### ISSUE TITLE
Scout2 does not work in the us-gov-west-1 region

### ISSUE THREAD

**Issue by nniehoff** [nccgroup/Scout2#200]
I ran scout2 with the us-gov-west-1 region the report came back with 0 resources with the exception of IAM where it found all of my resources.

**Comment by l01cd3v** [comment]
Did you run it with `--partition-name aws-us-gov` ?

**Comment by nniehoff** [comment]
Looks like it works, thanks.

**Comment by l01cd3v** [comment]
Cool !
