### ISSUE TITLE
Throttling on ListClusters 

### ISSUE THREAD

**Issue by sh1n0b1** [nccgroup/Scout2#205]
I'm still getting throttling errors using the latest version of the code:

`An error occurred (ThrottlingException) when calling the ListClusters operation (reached max retries: 4): Rate exceeded
               14/14                0/0`

**Comment by l01cd3v** [comment]
This is strange, "ThrottlingException" is one of the codes that is supposed to be caught...

https://github.com/nccgroup/Scout2/blob/594935039085553081349e6fcbff3c7a6e9ddfd9/AWSScout2/utils.py#L72

How many clusters / instances do you need to repro this issue?

**Comment by j4v** [comment]
Closing as outdated and potentially FP.
