### ISSUE TITLE
Scout2 reports Security Groups attached to ENI as unused

### ISSUE THREAD

**Issue by bradenwright** [nccgroup/Scout2#206]
Elastic Network Interfaces with SG's attached are showing as ununsed as well.  Already open issues for EMR, ALB's

**Comment by l01cd3v** [comment]
Thanks I'll look into these

**Comment by l01cd3v** [comment]
Out of curiosity, what are these ENIs attached to?

**Comment by l01cd3v** [comment]
This should be fixed
