### ISSUE TITLE
Role switching with credentials.csv not working

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#208]
Role switching does not work when passing in the credentials through a csv.

**Comment by l01cd3v** [comment]
Yeah, this is intended; support for CSV was just meant to enable one-off runs. If you want to use role switching, you'll need to configure a source profile and a role profile, just like what you'd do when using the AWS CLI.

**Comment by jjegg** [comment]
What I was trying to say, is with the source and role profile configured within .aws/config the role switching does not work when you are passing the credentials in the csv.

**Comment by l01cd3v** [comment]
Yes, this is on purpose. If you want the ability to switch roles, you'll need to configure your credentials in the .aws/credentials config file.
