### ISSUE TITLE
 SNS notification for "Danger " Signal Resources 

### ISSUE THREAD

**Issue by cvemula1** [nccgroup/Scout2#212]
I am looking for the Possible solution for Sending the alerts to SNS notification for the danger alerts

**Comment by l01cd3v** [comment]
This is currently out of this tool's scope. I have been thinking about solutions that do the following, but am unlikely to implement it anytime soon:

1. Run scout2 and store the report in S3
2. Trigger a lambda function on S3 PutObject in the receiving bucket
3. Have the lambda function load the scout2 JSON config file, iterate through each service's findings, and send an SNS notification.

If you end up creating such a tool and open-source it, please let me know and I'll be happy to put a reference to it somewhere in the documentation !

**Comment by cvemula1** [comment]
Thanks for the above solution. is this json file generating on each service help us with report generating commands

We are actually planning to take the "Danger" alert which is from json file and Triggering via SNS, so that only critical issues will be alerted. Can you please give us some insights on How this red color danger signal is pipe lined.
We are happy to share the info once we get success in this

**Comment by l01cd3v** [comment]
The findings are stored along with the configuration in the JSON datastructure stored in `scout2-report/inc-awsconfig/aws_config-<profile_name>.js`. The first line of the file breaks the JSON compability, it is used to declare the variable in the report's JS.

A simple way to get the data out of the report would be like that:

```
tail scout2-report/inc-awsconfig/aws_config-l01cd3v-scout2.js -n +2 | jq '.services[].findings[]'
```

This command outputs the file's contents (but skip the first line) then passes the valid JSON payload to jq and prints all the findings. Then you'd want do do some additional filtering on the value of the level (danger) and check whether the list of items is empty or not.

**Comment by cvemula1** [comment]
Thanks much for the reply. I will try this and let you know my findings

**Comment by cvemula1** [comment]
Findings#
**We are unable to find all the flagged resources from the above command
** We see 6 Danger items which are highlighted in Red
**************************************************************************************************************
tail aws_config-rahul.js  -n +2 | jq '.services[].findings[]'
{
  "checked_items": 0,
  "dashboard_name": "Stacks",
  "description": "Role passed to stack",
  "flagged_items": 0,
  "items": [],
  "level": "danger",
  "path": "cloudformation.regions.id.stacks.id",
  "rationale": "Passing a role to CloudFormation stacks may result in privilege escalation beause IAM users with privileges within the CloudFormation scope implicitly inherit the stack's role's permissions.",
  "service": "CloudFormation"
}
{
  "checked_items": 1,
  "dashboard_name": "Configuration",
  "description": "Global service logging duplicated",
  "flagged_items": 0,
  "id_suffix": "IncludeGlobalServiceEvents",
  "items": [],
  "level": "warning",
  "path": "cloudtrail",
  "rationale": "Global service logging is enabled in multiple Trails. While this does not jeopardize the security of the environment, duplicated entries in logs increase the difficulty to investate potential incidents.",
  "service": "CloudTrail"
}
{
  "checked_items": 1,
  "dashboard_name": "Configuration",
  "description": "Global services logging disabled",
  "flagged_items": 1,
  "id_suffix": "IncludeGlobalServiceEvents",
  "items": [
    "cloudtrail.IncludeGlobalServiceEvents"
  ],
  "level": "danger",
  "path": "cloudtrail",
  "rationale": "API activity for global services such as IAM and STS is not logged. Investigation of incidents will be incomplete due to the lack of information.",
  "service": "CloudTrail"
}
{
  "checked_items": 14,
  "dashboard_name": "Trails",
  "description": "Log file validation disabled",
  "flagged_items": 0,
  "id_suffix": "LogFileValidationDisabled",
  "items": [],
  "level": "danger",
  "path": "cloudtrail.regions.id.trails.id",
  "rationale": "The lack of log file validation prevents one from verifying the integrity of the log files.",
  "service": "CloudTrail"
}
{
  "checked_items": 14,
  "dashboard_name": "Trails",
  "description": "Logging disabled",
  "flagged_items": 1,
  "id_suffix": "IsLogging",
  "items": [
    "cloudtrail.regions.us-east-1.trails.97dca2b4cdb50fe74924ca32e6cf837d2ea87e51.IsLogging"
  ],
  "level": "danger",
  "path": "cloudtrail.regions.id.trails.id",
  "rationale": "Logging is disabled for a given Trail. Depending on the configuration, logs for important API activity may be missing.",
  "service": "CloudTrail"
}
{
  "checked_items": 14,
  "dashboard_name": "Regions",
  "description": "Not configured",
  "flagged_items": 0,
  "id_suffix": "NotConfigured",
  "items": [],
  "level": "danger",
  "path": "cloudtrail.regions.id",
  "rationale": "CloudTrail is not configured, which means that API activity is not logged.",
  "service": "CloudTrail"
}
{
  "checked_items": 5,
  "dashboard_name": "Alarms",
  "description": "Alarm without action",
  "flagged_items": 0,
  "id_suffix": "NoActions",
  "items": [],
  "level": "warning",
  "path": "cloudwatch.regions.id.alarms.id",
  "rationale": "Each alarm should have at least one action",
  "service": "CloudWatch"
}
*********************************************************************************************************

This above output is not matching with the HTML report. Give us some insights on this

**Comment by l01cd3v** [comment]
This items attribute for each finding lists the path to the resource flagged. For example, in the snippet below (copied from your data), you can see that items is a list with 1 element, whose value is

cloudtrail.regions.us-east-1.trails.97dca2b4cdb50fe74924ca32e6cf837d2ea87e51.IsLogging

```
{
"checked_items": 14,
"dashboard_name": "Trails",
"description": "Logging disabled",
"flagged_items": 1,
"id_suffix": "IsLogging",
"items": [
"cloudtrail.regions.us-east-1.trails.97dca2b4cdb50fe74924ca32e6cf837d2ea87e51.IsLogging"
],
"level": "danger",
"path": "cloudtrail.regions.id.trails.id",
"rationale": "Logging is disabled for a given Trail. Depending on the configuration, logs for important API activity may be missing.",
"service": "CloudTrail"
}
```

This should match the HTML report that will mention one trail is disabled. All the coloring/display of the name, etc... is a UI function. If you want to extract resource information from this, look into the Scout2Listall too, for which I just published some information on the wiki page at https://github.com/nccgroup/Scout2/wiki

**Comment by cvemula1** [comment]
## We ran the below command to get the danger items
############################################################################# 
 tail scout2-report/inc-awsconfig/aws_config.js -n +2 | jq '.services[].findings[]' | grep -v 'warning' | grep -A4 'danger'
  "level": "danger",
  "path": "cloudformation.regions.id.stacks.id",
  "rationale": "Passing a role to CloudFormation stacks may result in privilege escalation beause IAM users with privileges within the CloudFormation scope implicitly inherit the stack's role's permissions.",
  "service": "CloudFormation"
}
--
  "level": "danger",
  "path": "cloudtrail",
  "rationale": "API activity for global services such as IAM and STS is not logged. Investigation of incidents will be incomplete due to the lack of information.",
  "service": "CloudTrail"
}
--
  "level": "danger",
  "path": "cloudtrail.regions.id.trails.id",
  "rationale": "The lack of log file validation prevents one from verifying the integrity of the log files.",
  "service": "CloudTrail"
}
--
  "level": "danger",
  "path": "cloudtrail.regions.id.trails.id",
  "rationale": "Logging is disabled for a given Trail. Depending on the configuration, logs for important API activity may be missing.",
  "service": "CloudTrail"
}
--
  "level": "danger",
  "path": "cloudtrail.regions.id",
  "rationale": "CloudTrail is not configured, which means that API activity is not logged.",
  "service": "CloudTrail"
}
--
  "level": "danger",
  "path": "ec2.regions.id.vpcs.id.security_groups.id.rules.id.protocols.id.ports.id.cidrs.id.CIDR",
  "rationale": "N/A",
  "service": "EC2"
}
--
  "level": "danger",
  "path": "ec2.regions.id.vpcs.id.security_groups.id.rules.id.protocols.id.ports.id.cidrs.id.CIDR",
  "rationale": "N/A",
  "service": "EC2"
}
#######################################################################
##Below is the Screenshot of findings for the Ec2 Instance security group
![error](https://user-images.githubusercontent.com/19313298/33031611-6a99e7fa-cde4-11e7-8ad9-f2880d1087bf.png)



** This image data is not matching with the above fetched script from Shell command or the above findings data which i posted 

Is there anyway we can parse the HTML report to notify "danger" with name of that particular resource ?

**Comment by l01cd3v** [comment]
I'm not sure what you meant in your last comment - I just published documentation that I think should help you extract the information you need:

https://github.com/nccgroup/Scout2/wiki/HowTo:-Exporting-and-Programmatically-Access-of-Scout2-Data

**Comment by cvemula1** [comment]
Hi Do you have further work around this issues.

Did you notify anybody who successfully implemented notification of findings ?
