### ISSUE TITLE
Other outputs

### ISSUE THREAD

**Issue by ccodingsKILLS** [nccgroup/Scout2#213]
Hi there, 

Very good programme! However, I am hoping to generate alternative outputs other than html. Is this functionality in-built currently, or where can I edit code to perform this?

Just looking for some direction on this matter. Thanks!

**Comment by l01cd3v** [comment]
Yes, the tool supports arbitrary output, though creating a custom format requires a fair amount of work. I'll try to write some documentation for this. In the meantime, feel free to look at the code of the Scout2Listall tool (exports to CSV) which uses the format_listall_output and generate_listall_output functions.

**Comment by l01cd3v** [comment]
FYI, I started to work on the [wiki](https://github.com/nccgroup/Scout2/wiki) and the Scout2Listall information is pretty much complete

**Comment by ccodingsKILLS** [comment]
This is great!

**Comment by ccodingsKILLS** [comment]
by the way, can you please provide some information on how I can get arbitrary output as opposed to an HTML doc?

**Comment by l01cd3v** [comment]
I just added a wiki page for this:

https://github.com/nccgroup/Scout2/wiki/HowTo:-Exporting-and-Programmatically-Access-of-Scout2-Data
