### ISSUE TITLE
Bug: Regions filter empty

### ISSUE THREAD

**Issue by lgap** [nccgroup/Scout2#216]
The regions filter does not show any text; all entries remain empty.
![scout2regionempty](https://user-images.githubusercontent.com/34092979/33371838-4cc89400-d4fc-11e7-85df-e97d863f176a.jpg)

**Comment by l01cd3v** [comment]
This should be fixed now

**Comment by lgap** [comment]
Thank you for the update; however this bug does not seem to be resolved. 
![scout2emptyregionsfilter20171205](https://user-images.githubusercontent.com/34092979/33600540-d6346898-d9a9-11e7-9b76-76420b491b35.jpg)

Maybe it is because I'm running Scout2 with specific (limited) regions due to the tool crashing when I run it without that limitation. (Windows; Python 2.7; crash after Fetching SNS config message: can't start new thread/MemoryError. Would be great if the tool can be executed with a thread/Memory limit?)

**Comment by l01cd3v** [comment]
The regions filter is only available for region-enabled services - Which page were you on when you saw this? This would be typical for IAM / S3 / main dashboard...

Have you tried --thread-config 1 to see if this helps w/ the crash ? 

Can you give me more info about your hw : how much DRAM / CPUs do you have?

**Comment by lgap** [comment]
This was the home screen. When I go to the EC2 instances then it does show.

The --thread-config 1 resolves the problem. 
Please add this on the documentation page; this helps.

My Windows 7 Enterprise has 8G RAM with a Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz, 2301 Mhz, 2 Core(s), 4 Logical Processor(s)

Thank you.
