### ISSUE TITLE
Extra package needed

### ISSUE THREAD

**Issue by hposca** [nccgroup/Scout2#220]
I installed Scout2 through pip and when I tried to run it the following message appeared:

```bash
$ Scout2 --help                                                                                                                              
Error: Scout2 depends on the opinel package. Install all the requirements with the following command:
  $ pip install -r requirements.txt
'module' object has no attribute 'SSL_ST_INIT'
```

Strangely, the `opinel` package was already installed :/
Googling for the error message I found that I didn't have the pyOpenSSL package installed. So after doing:

```bash
$ sudo -H pip install --upgrade pyOpenSSL
```

Scout2 started working \o/

Don't know if this is a fault on `opinel` or `Scout2` for not pulling `pyOpenSSL` during the installation via `pip` :/

This is the info of the machine I'm using:

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.2
DISTRIB_CODENAME=sonya
DISTRIB_DESCRIPTION="Linux Mint 18.2 Sonya"

Linux thinkpad 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Anyway, I tested Scout2 and it gave a very interesting report :smile: 
Keep doing the good work :+1:

**Comment by l01cd3v** [comment]
Thanks - I couldn't repro this issue. Which desktop do you use for Mint ? Cinnamon or MATE ?

**Comment by hposca** [comment]
I'm using Cinnamon. Do you think this may have something related to it? :confused: 

```bash
$ echo $DESKTOP_SESSION
cinnamon
$ wmctrl -m
Name: Mutter (Muffin)
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

Thanks

**Comment by l01cd3v** [comment]
Got the same values in a test machine and didn't need to manually install pyOpenSSL. Not sure what happened in your environment.

**Comment by hposca** [comment]
Tested now within a new Virtual Machine and didn't have to install it :confused:

Closing the issue.

Thank you very much for your time.
