### ISSUE TITLE
Running Scout2 from an EC2 Instance

### ISSUE THREAD

**Issue by InforSecAssurance** [nccgroup/Scout2#222]
Hi

I want to use Scout2 inside an EC2 instance to run scans - but I am having a problem with the output. Essentially I want to grab the HTML output, drop it in an S3 bucket and use that on a static website hosted from the S3.

How would you recommend doing this?

**Comment by l01cd3v** [comment]
Use the AWS CLI to sync the report to your bucket ?

```
aws s3 sync scout2-report s3://your-bucket-name
```

**Comment by InforSecAssurance** [comment]
Great - but once the report is dumped to S3, can I open it up as a webpage, because it seems to require all the supporting json files to do anything useful, and even when the supporting files are in the same folder, the HTML file can't do anything useful when opened

**Comment by l01cd3v** [comment]
Yes this just works, I did it on my test account. The JSON data structure is actually a JavaScript file so loading it works regardless of where things are stored. 

Are you sure you copied he entire scout2-report folder ?
