### ISSUE TITLE
Add ability to whitelist checks we're ok with failing

### ISSUE THREAD

**Issue by rayterrill** [nccgroup/Scout2#225]
Sometimes we have things we don't want to configure (for monetary reasons, etc). There probably should be some way to whitelist those options to stop them from showing up on the report forever.

**Comment by l01cd3v** [comment]
This is already possible; there are 2 different options to do so:

1. Use a custom ruleset if an entire rule does not apply. Refer to https://github.com/nccgroup/Scout2/wiki/HowTo:-Use-with-a-custom-ruleset
2. Use a list of exceptions if you only wish to whitelist a few resources but keep the rule. Refer to https://github.com/nccgroup/Scout2/wiki/HowTo:-Create-and-use-a-list-of-exceptions

You may of course use a combination of both as well.
