### ISSUE TITLE
Issue saving Scout2 Web Archive output

### ISSUE THREAD

**Issue by cloudpayload** [nccgroup/Scout2#227]
Hi Team,

I am running Scout2 on mac and Scout2 reports open fine on safari.
But facing issue saving and reopening the file.
It is showing as a duplicate header file.

Is there a fix for this.

Thanks,
Saurabh

<img width="1243" alt="problem-window" src="https://user-images.githubusercontent.com/20483931/33777478-991a3d58-dc0a-11e7-86b8-d1c8a3f4a9f7.png">

**Comment by l01cd3v** [comment]
Does this happen in other browsers too? Which version of Scout2 are you using? How are you opening the report?

**Comment by cloudpayload** [comment]
Thanks for getting back.

I am running this report from mac and default output is safari, I am unable to open the saved webarchive file in other browser. The version is latest Scout2, Bump version to 3.0.0.
I am trying to open the report HTML file in Safari.

**Comment by j4v** [comment]
Closed as non-fix.
