### ISSUE TITLE
Error in Scout2 run

### ISSUE THREAD

**Issue by sandeep-sks** [nccgroup/Scout2#239]
I am getting following error, not sure whats going wrong here. Kindly help. 

Fetching Direct Connect config...
             regions        connections
Error: could not fetch directconnect configuration.
can't start new thread
Fetching ElastiCache config...
             regions           clusters    security_groups
Error: could not fetch elasticache configuration.
can't start new thread
Fetching Route53 config...
Error: could not fetch route53 configuration.
can't start new thread
Fetching SNS config...
             regions             topics      subscriptions
Error: could not fetch sns configuration.
can't start new thread
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\Scout2.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\AWSScout2\__main__.py", line 71, in main
    aws_config = report.jsrw.to_dict(aws_config)
  File "c:\python27\lib\site-packages\AWSScout2\output\js.py", line 66, in to_dict
    return json.loads(json.dumps(config, separators=(',', ': '), cls=Scout2Encoder))
  File "c:\python27\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "c:\python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
MemoryError

**Comment by l01cd3v** [comment]
You're likely running the tool from a VM / server that doesn't meet the hardware requirements. See https://github.com/nccgroup/Scout2#computing-resources.

**Comment by sandeep-sks** [comment]
Thanks for your reply. I have been running it on a high-end laptop (Win 10 Enterprise) laptop. I will retry it on another machine to rule out any environmental issues.

**Comment by l01cd3v** [comment]
Strange - You can also try to run the tool with `--thread-config 1` and see if this works. It takes values between 1 and 5, 4 being the default. The lower the number, the less threads will be used when fetching the config.

**Comment by j4v** [comment]
@sandeep-sks could you provide an update on this issue please?
