### ISSUE TITLE
Adding Regions

### ISSUE THREAD

**Issue by commercialeer** [nccgroup/Scout2#240]
First and foremost, I am a huge fan of this tool, and I appreciate the work that goes into maintaining it.  It looks like Scout2, in its current form, doesn't check the new Paris region (EU-WEST-3).  Any idea when it will be added?  How do you usually handle new regions?  Thanks.

**Comment by l01cd3v** [comment]
I haven't tried to run Scout2 in Paris but, as soon as boto3 adds support for a region, Scout2 supports it. Make sure to upgrade boto3 to the latest and that the CLI supports the region, then Scout2 should pick it up automatically.

**Comment by commercialeer** [comment]
That makes sense.  Thanks again for the work on this, it's immensely helpful!

**Comment by j4v** [comment]
The current version of boto3 supports the Paris (eu-west-3) region.
