### ISSUE TITLE
CSV Credential support?

### ISSUE THREAD

**Issue by arvinddoraiswamy** [nccgroup/Scout2#245]
It appears that Scout2 has csv-credential support. So I tried creating a file just like the one you get when you create a new Access key in IAM (download CSV credentials) and using it but it fails with an error saying:

"Error could not find AWS credentials. Use the --help option for more information."

I've compared the Hex dumps for both CSV files and they look exactly alike - binary characters included. I'm thinking I'm doing something wrong when copying creds into the csv (by hand).

Any ideas?

**Comment by l01cd3v** [comment]
Can you let me know the exact arguments you used to run Scout2 ?

**Comment by arvinddoraiswamy** [comment]
iirc it was just..

./Scout2.py --csv-credentials <file.csv>

**Comment by l01cd3v** [comment]
Just successfully ran `Scout2 --csv-credentials test.csv`. Reading the CSV contents is actually pretty flexible, the only constraint is to find an value starting with 'AKIA', followed by the secret key.

Can you cat the contents of your file, redact anything that needs to be, and share it?

**Comment by arvinddoraiswamy** [comment]
Yeah, I wondered the same - it worked with a access key, secret key
downloaded from the AWS console. This was an internal program though that
generated a key pair and stored it in a CSV file so I could then use it
with Scout2. So I did all that and diffed it with the original file and
nothing was different, so I wonder what's wrong. Maybe the key I'm
generating is off, somehow.

I will try and get a sample of the file tomorrow and attach it here.
