### ISSUE TITLE
Fetching S3 config exception "'dict_keys' object does not support indexing"

### ISSUE THREAD

**Issue by orest-p** [nccgroup/Scout2#246]
Report generated with Scout2 version 3.2.0
Ruleset used: default
Env: Python 3.6.2 

In python 2.7 runs -  OK

bellow is the output:

Fetching RedShift config...
             regions           clusters   parameter_groups    security_groups
               15/15                0/0                0/0                0/0
Fetching RDS config...
             regions          instances    security_groups          snapshots   parameter_groups      subnet_groups
               15/15                0/0              15/15                0/0                0/0                0/0
Fetching Route53 config...
        hosted_zones
                 1/1
Fetching Route53Domains config...
             domains
                 0/0
Fetching S3 config...
             buckets
'dict_keys' object does not support indexing
'dict_keys' object does not support indexing'dict_keys' object does not support indexing
'dict_keys' object does not support indexing
'dict_keys' object does not support indexing'dict_keys' object does not support indexing

                 0/6
Fetching SES config...
             regions         identities
                 3/3                0/0
Fetching SNS config...
             regions             topics      subscriptions
                8/15                4/4                2/2

**Comment by orest-p** [comment]
fixed with replacing in services/s3.py
api_client = params['api_clients'][get_s3_list_region(params['api_clients'].keys()[0])]
with
api_client = params['api_clients'][get_s3_list_region(list(params['api_clients'].keys())[0])]

**Comment by l01cd3v** [comment]
Thanks, I'll work on this

**Comment by j4v** [comment]
@gebailey correct, this was fixed a while a go.

I've released under v3.2.1.

**Comment by brunson** [comment]
PyPi still has v3.2.0

**Comment by ineffyble** [comment]
I'm getting this too, installing via pip.

**Comment by j4v** [comment]
PyPi package 3.2.1 released, considered as closed.
