### ISSUE TITLE
Adding one more permission in Scout Policy

### ISSUE THREAD

**Issue by boodera** [nccgroup/Scout2#247]
For running **elbv2 describe-listeners** aws-command-reference on aws environment, Scout2 role/user policy need one more permission `"elasticloadbalancing:DescribeListeners"` to be added, which is not by default listed in the Scout2Policy IAM policy mentioned in the README file.

**Comment by l01cd3v** [comment]
Thanks, I'll update the default policy soon

**Comment by j4v** [comment]
A fix for this would be to recommend the following AWS managed policies instead of a custom policy:

- arn:aws:iam::aws:policy/ReadOnlyAccess
- arn:aws:iam::aws:policy/SecurityAudit

The added benefit is that it wouldn't be required to maintain a policy as part of the project.

**Comment by j4v** [comment]
Duplicate from https://github.com/nccgroup/Scout2/issues/243.

**Comment by j4v** [comment]
The documentation has been updated to recommend using Managed Policies.
