### ISSUE TITLE
iam:Passrole tagged as redflag while they are used by AWS for Autoscaling apps

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [nccgroup/Scout2#250]
Hi, 

I wanted to talk about the alert shown if iam:PassRole is used as part of a policy. When we configure AutoScaling, policies having this are configured automatically from AWS side to use Service-linked roles. Would appreciate if you guys help me understand if I am missing something here if i chose to ignore this alert based on above argument (confirming that the policy is not associated with any other role than one used for auto scaling) ?

Thanks for Help, 
Himanshu

**Comment by hb3b** [comment]
It's fine to disregard but you may want to consider restricting iam:PassRole to a specific resource/role.

**Comment by j4v** [comment]
Correct, PassRole is not an issue in itself, but you want to restrict who can carry that action following the principle of least privilege.
In this case, ensure that the role's trust policy is correctly configured.
