### ISSUE TITLE
Missing args in AWSScout2/rules/data/rulesets/default.json

### ISSUE THREAD

**Issue by benghaun** [nccgroup/Scout2#257]
For the default rulesets json file, the "vpc-subnet-with-default-acls.json" rule seems to be missing arguments. Looking at vpc-subnet-with-default-acls.json in AWSScout2/rules/data/findings shows that it expects 2 arguments, which are [ "Direction of traffic (ingress or egress)", "Corresponding target (source or destination)" ].

**Comment by j4v** [comment]
Correct, nice find - I'll fix this soon.
Will also lower from `Danger` to `Warning`.

Additionally I'm seeing that in the subnet view, you don't see what ACL is actually associated to the subnet (you have to go in the ACL view to find associated subnets). Will consider adding this.
