### ISSUE TITLE
Assume Role Policy Naming

### ISSUE THREAD

**Issue by jacobheath** [nccgroup/Scout2#260]
Hey Loic,
Any reason why when you click a role, the second row is titled `Assume Role Policy` when it actually describes the trust relationships of the things that are allowed to assume the clicked role? In the AWS console, there is a second tab titled `Trust Relationships` that I think describes the data a bit better. The way it currently is titled, it kind of looks like it is highlighting the assume role action in the below inline policy, but sometimes these will read differently.

Attached is a screenshot of what I am talking about:

![ss](https://user-images.githubusercontent.com/16947503/41628822-2a9bac9a-73db-11e8-841c-82d9da09a728.png)

![ss](https://user-images.githubusercontent.com/16947503/41628911-7def0fcc-73db-11e8-830b-c113d128e3fd.png)

**Comment by j4v** [comment]
Indeed the "Assume Role Policy" name is somewhat misleading (even though this policy is commonly referred to as the role's Assume Role Policy). It could be renamed "Role Trust Policy"  to clarify that this refers to the role's resource policy.

**Comment by j4v** [comment]
Changed to "Role Trust Policy".
