### ISSUE TITLE
AuthorizationError and AccessDenied

### ISSUE THREAD

**Issue by saryx123** [nccgroup/Scout2#261]
When running with SecurityAuditor privilege , as advised, few of the calls/checks return an error - 

An error occurred (AuthorizationError) when calling the ListSubscriptions operation: User: arn:aws:iam::ACCOUNTID#:user/USERNAME is not authorized to perform: SNS:ListSubscriptions on resource: arn:aws:sns:ap-south-1:ACCOUNTID#:*

An error occurred (AccessDenied) when calling the ListIdentityPolicies operation: User: arn:aws:iam::ACCOUNTID#:user/USERNAME is not authorized to perform: ses:ListIdentityPolicies

An error occurred (AccessDenied) when calling the ListIdentityPolicies operation: User: arn:aws:iam::ACCOUNTID#:user/USERNAME is not authorized to perform: ses:ListIdentityPolicies

**Comment by j4v** [comment]
You should use the https://github.com/nccgroup/AWS-recipes/blob/master/IAM-Policies/Scout2-Default.json policy to run Scout2.
Alternatively you may use the ReadOnlyAccess managed policy in conjunction with the SecurityAuditor policy.
