### ISSUE TITLE
How can we catch the error while running the Scout2 Report ?

### ISSUE THREAD

**Issue by cvemula1** [nccgroup/Scout2#263]
I'm running this tool for multiple accounts and i've seen there are some services missing during run time which is a shell script

Is anybody worked around to find the error ?

Thanks

**Comment by j4v** [comment]
Could you please elaborate on the issue or post output?

**Comment by cvemula1** [comment]
Here is the issue 
I'm running this scanning for multiple accounts, I say more than +30 on daily basis in between I'm getting some unknown errors during scanning let's say skipping some services or access denied. I just want to record this error and alerts whenever something goes wrong

**Comment by j4v** [comment]
You'll have to provide more details here:
- Are you running this with some custom code?
- Are you sure the errors aren't related to lack of privileges against the accounts you are running this?

Without more details or output little can be done to determine where the error lies. To me it doesn't sound like a Scout2 issue.

**Comment by cvemula1** [comment]
Are you sure the errors aren't related to lack of privileges against the accounts you are running this? Yes.
Is there any way we can catch that error ?

**Comment by j4v** [comment]
I can't help further if you don't provide concrete [error] output or trace.
