### ISSUE TITLE
Wiki Example - Arbitrary output using Scout2Listall

### ISSUE THREAD

**Issue by marcinguy** [nccgroup/Scout2#265]
I receive this error:

$ Scout2Listall --config /home/user/Scout2/AWSScout2/rules/data/findings/iam-user-without-mfa.json --format-file /home/user/Scout2/AWSScout2/rules/data/findings/iam-users-without-mfa.md
Traceback (most recent call last):
  File "/usr/local/bin/Scout2Listall", line 11, in <module>
    load_entry_point('AWSScout2==3.2.0', 'console_scripts', 'Scout2Listall')()
  File "/usr/local/lib/python2.7/dist-packages/AWSScout2/__listall__.py", line 76, in main
    pe = ProcessingEngine(ruleset)
  File "/usr/local/lib/python2.7/dist-packages/AWSScout2/rules/processingengine.py", line 22, in __init__
    self.rules[rule.path].append(rule)
AttributeError: 'Rule' object has no attribute 'path'

Any idea what am I doing wrong?

I have my report in /home/user/scout2-report/ and it works.

**Comment by j4v** [comment]
You'll want to remove the full path, e.g.
`$ Scout2Listall --config iam-user-without-mfa.json --format-file iam-users-without-mfa.md`

**Comment by marcinguy** [comment]
Followed your advice and wiki, hmmm ... tried this:

Have my report in /home/user/scout2-report/ my MD is in /home/user/Scout2/AWSScout2/rules/data/findings/iam-users-without-mfa.md

and execute this command in /home/user


$ Scout2Listall --config iam-user-without-mfa.json --format-file iam-users-without-mfa.md
Traceback (most recent call last):
  File "/usr/local/bin/Scout2Listall", line 11, in <module>
    load_entry_point('AWSScout2==3.2.0', 'console_scripts', 'Scout2Listall')()
  File "/usr/local/lib/python2.7/dist-packages/AWSScout2/__listall__.py", line 76, in main
    pe = ProcessingEngine(ruleset)
  File "/usr/local/lib/python2.7/dist-packages/AWSScout2/rules/processingengine.py", line 22, in __init__
    self.rules[rule.path].append(rule)
KeyError: u'iam.users.id'

**Comment by marcinguy** [comment]
Works! Thanks. I used the GitHub version and put the format file in /home/user/Scout2/AWSScout2/rules/data/findings/

than run it from /home/user directory as you suggested

`$ Scout2Listall --config iam-user-without-mfa.json --format-file iam-users-without-mfa.md`

However, when I install Scout2 from pip package, where should I put fromat file (--format-file iam-users-without-mfa.md)

**Comment by j4v** [comment]
In that case you will want to put the files where the package has been installed.

If you're using "advanced" features, your best bet is probably to use the repository + virtualenv.
