### ISSUE TITLE
S3 buckets not reporting

### ISSUE THREAD

**Issue by cjbischoff** [nccgroup/Scout2#278]
- Running the Scout2 with default parameters following error occurs

```
Fetching S3 config...
             buckets
'dict_keys' object does not support indexing
'dict_keys' object does not support indexing
                 0/2
```
When I do in fact have 2x S3 buckets

```
aws s3api list-buckets --query "Buckets[].Name"
[
    "com.devnull.security.logs.eng.uw2",
    "com.devnull.security.terraform.uw2"
]
```

**Comment by j4v** [comment]
Are you running the latest branch/release? This seems to be a duplicate:
https://github.com/nccgroup/Scout2/issues/246

**Comment by cjbischoff** [comment]
I am running 3.2.0 - not the latest branch/release.  I will update - seems to be the same issue - thank you
