### ISSUE TITLE
argument of type 'NoneType' is not iterable when scanning EC2 Config

### ISSUE THREAD

**Issue by museadmin** [nccgroup/Scout2#283]
When running your scanner I am seeing this output in the snapshot scanning 

`Fetching EC2 config...
             regions          instances    security_groups            volumes          snapshots network_interfaces
                 1/1            136/136            445/445            407/407         6799/24378              0/492argument of type 'NoneType' is not iterable
                 1/1            136/136            445/445            407/407        18283/24378              0/492argument of type 'NoneType' is not iterable
                 1/1            136/136            445/445            407/407        18753/24378              0/492argument of type 'NoneType' is not iterable`

Presumably you need to add a check for null somewhere. 

The tool runs to completion though so I would suggest that a this is a low priority.

**Comment by j4v** [comment]
Thanks for opening the issue @museadmin, could you please run the tool with --debug and provide the output?

**Comment by j4v** [comment]
@museadmin closed due to lack of feedback, can't isolate the origin of the error.

@SeanLeftBelow this seems like an unrelated issue
