### ISSUE TITLE
Report viewing problems with large AWS installs

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#297]
Opening the report in Chrome crashes the tab

The report is big... 645M aws_config.js

Tried with Firefox and it works, but when I try to access some of the data (like S3 vuln) it doesn't show.

Any ideas on what I could do?

**Comment by andresriancho** [comment]
Screenshot before tab crashes:

![screenshot from 2018-09-10 15-33-19](https://user-images.githubusercontent.com/865200/45316934-e58a0f00-b50e-11e8-8d55-f9a13eb21f5c.png)

**Comment by andresriancho** [comment]
Checked `dmesg`:

```
[lun sep 10 15:15:20 2018] mmap: chrome (25380): VmData 4295053312 exceed data ulimit 4294967296. Update limits or use boot option ignore_rlimit_data.
[lun sep 10 15:15:20 2018] traps: chrome[25380] trap invalid opcode ip:5600cad97e62 sp:7ffec2270018 error:0 in chrome[5600c6604000+6378000]
[lun sep 10 15:17:44 2018] traps: chrome[26168] trap invalid opcode ip:5600cad97e62 sp:7ffec226ffb8 error:0 in chrome[5600c6604000+6378000]
```

It seems that the kernel is killing it!

PS: My workstation has 64B RAM

**Comment by j4v** [comment]
This is most likely because of the size of the json file created by Scout. Not sure how to fix this in the tool per say. I'd recommend splitting the analysis between services/regions.

**Comment by j4v** [comment]
Closed as referenced in https://github.com/nccgroup/Scout2/issues/298.

**Comment by j4v** [comment]
Closing this and labeling as `wontfix`. 

This is a known issue and a limitation of browsers' memory management. In addition, generating such a large report is considered as an edge case.
