### ISSUE TITLE
allocation size overflow in JavaScript console

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#298]
It looks like the JS code is having issues with the large report too. Getting this in the JavaScript console when clicking on one of the S3 findings:

![screenshot from 2018-09-10 15-50-38](https://user-images.githubusercontent.com/865200/45317779-5fbb9300-b511-11e8-9d96-71929c3660fb.png)

The link I'm trying to follow:

```
file:///home/eth/tools/Scout2/scout2-report/report.html#services.s3.findings.s3-bucket-world-Put-policy.items
```

I'm clicking there:

![screenshot from 2018-09-10 15-49-40](https://user-images.githubusercontent.com/865200/45317813-75c95380-b511-11e8-8796-0018fec6896c.png)

And there are quite a few S3 findings shown in the main report page:

![screenshot from 2018-09-10 15-49-23](https://user-images.githubusercontent.com/865200/45317827-82e64280-b511-11e8-97f8-c9849c181624.png)

Any ideas on how to solve / workaround this one?

**Comment by andresriancho** [comment]
This is a known limitation for tools like Jupyter (see the table with the different browsers):
https://jupyterlab.readthedocs.io/en/latest/user/file_formats.html#delimiter-separated-values

**Comment by andresriancho** [comment]
Found workaround, will split my assessment in batches by service, eg:

```
python Scout2.py --services awslambda cloudformation cloudtrail cloudwatch directconnect --report-dir=batch-1 --debug --force
```

**Comment by j4v** [comment]
This is most likely because of the size of the json file created by Scout. Not sure how to fix this in the tool per say. I'd recommend splitting the analysis between services/regions.

**Comment by j4v** [comment]
That would work, yes. Although this is really an edge case at this point.

**Comment by j4v** [comment]
Closing this and labeling as `wontfix`. 

This is a known issue and a limitation of browsers' memory management. In addition, generating such a large report is considered as an edge case.
