### ISSUE TITLE
could not connect to the endpoint URL: "https://ec2.eu-west-1.amazonaws.com/

### ISSUE THREAD

**Issue by nitinitare** [nccgroup/Scout2#299]
Hi I am new to scout2, I have installed it but when i run the command "scout2" it freezes at final stage , out of 15 regions 14 is completed but only one i.e eu-west-1 is not able to complete Fetching EC2 Config and gives following error message "Could not connect to the endpoint URL : "https://ec2.eu-west-1.amazonaws.com/""

**Comment by j4v** [comment]
Please provide full output of a run with the `--debug` flag.

**Comment by j4v** [comment]
Closed due to lack of followup.
