### ISSUE TITLE
False positive in Security group whitelists AWS CIDRs

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#305]
https://github.com/nccgroup/Scout2/blob/15d20ce68c0c9328c583ff3ba172efc8326153c8/AWSScout2/rules/data/findings/ec2-security-group-whitelists-aws.json

`Security group whitelists AWS CIDRs` is being triggered on some security groups when`x.y.z.w/32` is allowed in the ingress traffic.

Because this is a `/32` I believe it should be ignored by the rule.

**Comment by l01cd3v** [comment]
I disagree - if you whitelisted a /32 that was not an elastic IP in your account, you have very little control on what that IP will become.

In many cases, use of security groups / peering / etc may let you achieve similar results without the use of an IP address. If this is a valid use case for whitelisting a single IP, then this is when you'd want to save this as an exception.

**Comment by j4v** [comment]
Agreed and closed.
