### ISSUE TITLE
TCP port open to all

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#311]
In most cases `TCP port open to all` duplicates findings from `FTP port open`, `NFS port open`, etc.

If a security group opens port 21 to all, this is flagged in both `TCP port open to all` and `FTP port open`. Ideally it should only be flagged in `FTP port open` (which is less generic)

**Comment by j4v** [comment]
Agreed and closed.

In terms of renaming I'm thinking of putting all the "X port open" issues under a single "Sensitive port open" issue.
