### ISSUE TITLE
https://nccgroup.github.io/Scout2/ returns a 404

### ISSUE THREAD

**Issue by swedishmike** [nccgroup/Scout2#317]
When I try to reach the url referenced at the top of this repo I get a 404. Is that site moved to the Wiki url that's referenced in the readme or is there some other issue here?

![image](https://user-images.githubusercontent.com/8100625/47427978-ca572400-d789-11e8-9502-925a88220b71.png)

**Comment by j4v** [comment]
Indeed, I'm not certain what that [used to?] point to. You're correct that all the info is in the README and Wiki.

**Comment by swedishmike** [comment]
Cheers @j4v - maybe someone with access to the repo could just change that link to point to the Wiki?

**Comment by j4v** [comment]
Yeah, I'd like to figure out what it pointed to first though.

**Comment by l01cd3v** [comment]
This repo used to have a github-pages branch, which is what this pointed to.

**Comment by j4v** [comment]
This branch appeared to be stale and was [now obviously mistakenly] deleted. I've looked at the GH reflogs but it doesn't seem to be there anymore.

@l01cd3v would you happen to have a local copy of `gh-pages`?

**Comment by l01cd3v** [comment]
re-pushed the gh-pages branch. Unsure why the https link is not working, maybe some caching issue? For now it's accessible via http, so I uploaded the link on the home page as well.
