### ISSUE TITLE
No `--output` Option

### ISSUE THREAD

**Issue by moloch--** [nccgroup/Scout2#84]
The report can only be written to the cwd, there should be an `--output` or `--report` command line option to specify where to output the file.

**Comment by l01cd3v** [comment]
It's somewhat tricky as the report depends on many JS/CSS files from the inc-* folders in the report. Do you expect the tool to copy all of these folderes and files too? What do you expect to specify as the argument? The path to the report or the new report name?

FYI, I won't have time to work on such feature for a while.

**Comment by moloch--** [comment]
Yea after looking a bit more into the code it looks to be a bit trickier than I originally thought. You could potentially inline all of the JS/CSS resources so that a single `.html` is produced. It's not a big deal, just a convenience feature.

**Comment by mbassett** [comment]
This seems like it still should be pretty easy..   

cd ~/gits/Scout2
mkdir output
cp -r inc-* output
cp report.html output
cd output

All that is really necessary is a 'bundle' of files that should go in a web directory either as a zip/tgz/etc  or just a directory.  Either seem fine to me.

**Comment by l01cd3v** [comment]
The dev branch now creates a folder that contains all the necessary files. For now the argument name is "report-dir" but I may change it before I merge dev into master.

$ ./Scout2.py --report-dir foobar
[....]

$ ls -la foobar/
total 136
drwxr-xr-x  7 loic loic   4096 Apr 12 05:43 .
drwxr-xr-x 11 loic loic   4096 Apr 12 05:43 ..
drwxr-xr-x  2 loic loic   4096 Apr 12 05:43 inc-awsconfig
drwxr-xr-x  5 loic loic   4096 Apr 12 05:43 inc-bootstrap
drwxr-xr-x  2 loic loic   4096 Apr 12 05:43 inc-handlebars
drwxr-xr-x  2 loic loic   4096 Apr 12 05:43 inc-jquery
drwxr-xr-x  2 loic loic   4096 Apr  6 16:08 inc-scout2
-rw-r--r--  1 loic loic 106939 Apr 12 05:43 report.html

**Comment by Valien** [comment]
I like this custom output idea as well. I'm dockerizing the app and only want to dump the reports to a mounted volume, not the whole Scout2 program. Thanks for looking into this!

**Comment by l01cd3v** [comment]
Implemented: by default everything will be written under scout2-report. If a different path is desired, use --report-dir
