### ISSUE TITLE
ELBs not included in external attack surface report

### ISSUE THREAD

**Issue by lxcode** [nccgroup/Scout2#87]
Currently, public IPs of ELBs aren't shown in the external attack surface report, which can lead to overlooking externally exposed ports. It would be great if these were in that report, perhaps with a notation like (ELB) next to them.

**Comment by shivankar-madaan** [comment]
@lxcode are you talking about the public IP of ELB's.... they keep dynamically changing,so not sure if the above request is possible to implement.
If your talking about the public IP's of the servers behind/on the ELB,yes then that can be done(although the instanceId is displayed with every ELB)

**Comment by l01cd3v** [comment]
There is now one external attack surface report per service (e.g. ec2, elb, elbv2, rds, ...) as well as one per service group (e.g. compute, database, ...)
