### ISSUE TITLE
KeyError: 'security_groups'

### ISSUE THREAD

**Issue by jweller** [nccgroup/Scout2#89]
Saw the following when running Scout2 against one of my AWS accounts:

> Fetching CloudTrail config...
> Fetching EC2 config...
>               region   Elastic LBs   Elastic IPs          VPCs   Sec. Groups     Instances
>            us-east-1         0/103         41/41           5/5       352/352       245/245
>       ap-northeast-1           0/0           0/0           0/0           1/1           0/0
>            sa-east-1           0/0           0/0           0/0           1/1           0/0
>       ap-southeast-1           0/0           0/0           0/0         12/12           0/0
>       ap-southeast-2           0/0           0/0           0/0         12/12           0/0
>            us-west-2           0/0           0/0           0/0           1/1           0/0
>            us-west-1           0/0           0/0           0/0           1/1           0/0
>         eu-central-1           0/0           0/0           0/0           0/0           0/0
>            eu-west-1           0/0           0/0           0/0         12/12           0/0
> Fetching IAM users...
> 82/82
> Fetching IAM groups...
> 30/30
> Fetching IAM roles...
> 35/35
> Fetching IAM policies...
> 16/16
> Fetching IAM credential report...
> Fetching IAM password policy...
> Fetching RDS config...
> Fetching Redshift config...
> Fetching S3 buckets config...
> 98/98
> Analyzing VPC config...
> Traceback (most recent call last):
>   File "./Scout2.py", line 237, in <module>
>     sys.exit(main(args))
>   File "./Scout2.py", line 125, in main
>     analyze_vpc_config(aws_config, args.ip_ranges, args.ip_ranges_key_name)
>   File "/Users/jweller/Scout2-master/Scout2/AWSScout2/utils_vpc.py", line 20, in analyze_vpc_config
>     go_to_and_do(aws_config, aws_config['services']['ec2'], ['regions', 'vpcs', 'elbs'], ['services', 'ec2'], list_resources_in_security_group, callback_args)
>   File "/Users/jweller/Scout2-master/Scout2/AWSScout2/utils.py", line 155, in go_to_and_do
>     go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
>   File "/Users/jweller/Scout2-master/Scout2/AWSScout2/utils.py", line 155, in go_to_and_do
>     go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
>   File "/Users/jweller/Scout2-master/Scout2/AWSScout2/utils.py", line 147, in go_to_and_do
>     callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
>   File "/Users/jweller/Scout2-master/Scout2/AWSScout2/utils_vpc.py", line 62, in list_resources_in_security_group
>     sg = get_object_at(aws_config, sg_path)
>   File "/Users/jweller/Scout2-master/Scout2/AWSScout2/utils.py", line 127, in get_object_at
>     o = o[p]
> KeyError: 'security_groups'

**Comment by l01cd3v** [comment]
Seems similar to #91 - Will look into it.

**Comment by deepakantiya** [comment]
Same error on my screen as well - 

Analyzing VPC config...
Traceback (most recent call last):
  File "Scout2.py", line 237, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 125, in main
    analyze_vpc_config(aws_config, args.ip_ranges, args.ip_ranges_key_name)
  File "/home/dantiya/Downloads/nccgroup-Scout2-da7de21/AWSScout2/utils_vpc.py", line 20, in analyze_vpc_config
    go_to_and_do(aws_config, aws_config['services']['ec2'], ['regions', 'vpcs', 'elbs'], ['services', 'ec2'], list_resources_in_security_group, callback_args)
  File "/home/dantiya/Downloads/nccgroup-Scout2-da7de21/AWSScout2/utils.py", line 155, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/home/dantiya/Downloads/nccgroup-Scout2-da7de21/AWSScout2/utils.py", line 155, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/home/dantiya/Downloads/nccgroup-Scout2-da7de21/AWSScout2/utils.py", line 147, in go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/dantiya/Downloads/nccgroup-Scout2-da7de21/AWSScout2/utils_vpc.py", line 62, in list_resources_in_security_group
    sg = get_object_at(aws_config, sg_path)
  File "/home/dantiya/Downloads/nccgroup-Scout2-da7de21/AWSScout2/utils.py", line 127, in get_object_at
    o = o[p]
KeyError: 'security_groups'

**Comment by l01cd3v** [comment]
Hi, I am having issue reproducing this issue. I just added some debug messages and a try/catch where I think the issue might happen. Could you give it a try?

Can you checkout the issue89 branch, run it with --debug, and send me the output?

Thanks

**Comment by jweller** [comment]
Thanks!

https://gist.github.com/jweller/a0f2849b44a26023fde2de841e44205d

**Comment by l01cd3v** [comment]
Thanks ! It looks like the issue comes from ELBs not having a security group. I don't know how/why that is possible. If possible, could you share with me the output of the following AWS CLI command?

aws elb describe-load-balancers

Feel free to obfuscate values and share it via gist again, or you can email me the raw data. My PGP key is at https://isecpartners.github.io/keys/lsimon.asc and you can email me via loic.simon [at] nccgroup [dot] trust

Thanks

**Comment by jweller** [comment]
@l01cd3v: I'm not sure I can make the entire output available (even privately), as there's quite a lot of production information in there.  I checked through the output and I do not see any ELBs without a value for 'SOURCESECURITYGROUP'.  However, we do have a handful of EC2 Classic ELBs (i.e., not in VPC) that have 'SOURCESECURITYGROUP' = "amazon-elb-sg	amazon-elb", but no 'SECURITYGROUPS' key.  Might it have something to do with EC2 Classic vs. VPC? Here's an obfuscated example of one of these EC2 Classic ELBs:

```
LOADBALANCERDESCRIPTIONS	foo-lb-9999999999.us-east-1.elb.amazonaws.com	Z3DZXXXX79N41H	2012-10-09T16:28:48.120Z	foo-lb-9999999999.us-east-1.elb.amazonaws.com	foo-lb	internet-facing	
AVAILABILITYZONES	us-east-1d
HEALTHCHECK	3	6	TCP:80	5	8
INSTANCES	i-deadb33f
LISTENER	80	HTTP	80	HTTP
LISTENER	80	HTTP	443	HTTPS	arn:aws:iam::111122223333:server-certificate/foo-bar-com-20180523
POLICYNAMES	AWSConsole-SSLNegotiationPolicy-foo-99999999999
OTHERPOLICIES	AWSConsole-SSLNegotiationPolicy-foo-bar
OTHERPOLICIES	foo-bar-ELBSecurityPolicy-2011-08
OTHERPOLICIES	AWSConsole-SSLNegotiationPolicy-foo-bar-1234567890
OTHERPOLICIES	AWSConsole-SSLNegotiationPolicy-foo-bar-1234567890
OTHERPOLICIES	AWSConsole-SSLNegotiationPolicy-foo-bar-1234567890
OTHERPOLICIES	AWSConsole-SSLNegotiationPolicy-foo-bar-1234567890
SOURCESECURITYGROUP	amazon-elb-sg	amazon-elb
```

And here's an example of a normal ELB in a VPC:

```
LOADBALANCERDESCRIPTIONS	awseb-e-m-AWSEBLoa-1234567890-2005711675.us-east-1.elb.amazonaws.com	Z3DXXXXQ79N41H	2014-11-19T20:04:51.470Z	awseb-e-m-AWSEBLoa-1234567890-2005711675.us-east-1.elb.amazonaws.com	awseb-e-m-AWSEBLoa-1234567890	internet-facing	vpc-99999999
AVAILABILITYZONES	us-east-1c
AVAILABILITYZONES	us-east-1a
AVAILABILITYZONES	us-east-1d
HEALTHCHECK	3	10	HTTP:80/health_check	5	5
INSTANCES	i-8badf00d
LISTENER	80	HTTP	443	HTTPS	arn:aws:iam::111122223333:server-certificate/foo-bar-com-04-2018
POLICYNAMES	ELBSecurityPolicy-2014-10
LISTENER	80	HTTP	80	HTTP
OTHERPOLICIES	ELBSecurityPolicy-2014-10
SECURITYGROUPS	sg-00bab10c
SOURCESECURITYGROUP	awseb-e-abc123def4-stack-AWSEBLoadBalancerSecurityGroup-98XXXXXW815T	111122223333
SUBNETS	subnet-1f002f00
SUBNETS	subnet-3f004f00
SUBNETS	subnet-5f006f00
```

**Comment by l01cd3v** [comment]
Ok, I finally had time to look it up, it's indeed due to EC2-Classic ELBs vs VPC ELBs. The answer is on the current AWS documentation athttp://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-getting-started.html. 

"If you selected a VPC as your network, you must assign your load balancer a security group that allows inbound traffic to the ports that you specified for your load balancer and the health checks for your load balancer.

Note
If you selected EC2-Classic as your network, you can continue to the next step. By default, Elastic Load Balancing provides a security group for load balancers in EC2-Classic."

**Comment by l01cd3v** [comment]
This should be fixed in master now

**Comment by l01cd3v** [comment]
@jweller, could you please confirm before I close the issue? Thanks for helping me troubleshoot this !

**Comment by jweller** [comment]
@l01cd3v thanks for the update! I got a different error this time.  Seems like there might be a missing rules file.  I can't find this iam-inline-group-policy-allows-sts-AssumeRole.json in the 'rules' directory.

> Failed to process rule defined in iam-inline-group-policy-allows-sts-AssumeRole.json
> 
> Traceback (most recent call last):
>   File "./Scout2.py", line 267, in <module>
>     sys.exit(main(args))
>   File "./Scout2.py", line 176, in main
>     aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
> KeyError: 'items'

**Comment by l01cd3v** [comment]
This rule is a parameterized rule that is used multiple times with various arguments. The definition is under rules/iam-inline-policy-for-role.json 

Can you run it with --debug and share the output? The traceback you shared is due to a later uncaught exception due to that rule processing failure. I just made a local change to catch these exceptions at the same time than rule processing fails; however, I'd like to figure out why processing the rule fails.

**Comment by jweller** [comment]
Sure thing.  Here's the latest output with --debug.
https://gist.github.com/jweller/6b9ad85cf62412060ee19f60de34735d

**Comment by l01cd3v** [comment]
This is the same gist as previously (with the 'no security_groups key error)

**Comment by jweller** [comment]
I just wiped my local repo then cloned again from master (`git clone https://github.com/nccgroup/Scout2.git -b master`).  Same output.

**Comment by deepakantiya** [comment]
Same error exists on my end as well..

**Comment by l01cd3v** [comment]
The new error was reported as issue #99 and should be fixed in the dev branch, merged in master soon.
I am not sure why the exception message for the security_groups key missing still happens though, I tried adding code to handle this exception separately.

Unfortunately I do not have access to an EC2-Classic enabled account so getting this right is a bit tricky. Could you please do the following for me: modify AWSScout2/utils_vpc.py and add the following line on line 86 (before or after the printException(e)):
    print('VPC ID: %s' % vpc_id)

Run it, and share with me what the vpc ID is? I expected it to be 'EC2-Classic' but I may have missed something. Thanks !

**Comment by deepakantiya** [comment]
I replaced line 86 with "print('VPC ID: %s' % vpc_id)"

The VPC ID -
Parsing ELBs...
VPC ID: vpc-4e5eb72b
VPC ID: vpc-4e5eb72b

Hope this should help you!

**Comment by jweller** [comment]
I had the same result as deepakantiya.  Everything has normal VPC IDs; nothing is showing as 'EC2-Classic' or anything like that.

**Comment by dpkant9** [comment]
So, I fired the command for only specific regions within US. It does works. But some how it does not work for EU and AP.

**Comment by l01cd3v** [comment]
I tried creating ELBs in EU and AP regions but no luck. I've pushed a more verbose debug message on the dev branch, could you checkout that branch, run it, and share the log?

**Comment by l01cd3v** [comment]
Is this still happening to anyone?

**Comment by jweller** [comment]
@l01cd3v everything's working fine for me in master now.  Thanks a lot for all your effort!

**Comment by l01cd3v** [comment]
Thanks !
