### ISSUE TITLE
graph visualisation

### ISSUE THREAD

**Issue by michaelfoley1** [nccgroup/Scout2#90]
It would be amazing if there was a way to visualise VPC's, instances, security groups and ELB rules through a graph. Presumably it would use D3.

**Comment by l01cd3v** [comment]
I would love to add this functionality but cannot commit on any deadline.

**Comment by j4v** [comment]
CloudMapper (https://github.com/duo-labs/cloudmapper) provides this functionality. 

Closing the issue as the feature isn't directly in line with Scout2's intended purpose.
