### ISSUE TITLE
Fail to Display "User without MFA"

### ISSUE THREAD

**Issue by sublimedamien** [nccgroup/Scout2#93]
Hello 

With the latest release of SCOUT2  v2.0.0rc4 the Item "User without MFA" is incorrect.
The  Item is "green" with all my user are MFA device enable. However i have a few users with no MFA device . 
I try with boto3 "1.2.3" and the latest release "1.3.1" no change .  

Thanks for your work.

**Comment by l01cd3v** [comment]
Hi,

This rule only flags IAM users that do not have an MFA device and have a login profile (i.e. password-based authentication already exists). I think that if you browse to the users view and look up these users, it should say "Password enabled: No". Could you please confirm?

Thanks

**Comment by sublimedamien** [comment]
Hi 

Yes your right . Sorry for this case open unnecessarily.

Best regards.
