### ISSUE TITLE
Missing regions in AP

### ISSUE THREAD

**Issue by bfmike** [nccgroup/Scout2#95]
Hi there are a couple of AP regions missing: Seoul and Mumbai.  Just wondering if there is an AWS API to list regions so that future new regions aren't missed??

Mike

**Comment by l01cd3v** [comment]
Thanks, I pushed a fix in the dev branch for this issue. Unfortunately dev is only working for python 2.7 now, I'm pending on another dependency to add support for Python3 to fix dev. As soon as the dev branch is works for Python 3, I'll merge it with Master.

**Comment by l01cd3v** [comment]
This should be fixed in Master now
