### ISSUE TITLE
Can't view reports on iPhone

### ISSUE THREAD

**Issue by bfmike** [nccgroup/Scout2#96]
Reports don't render properly when viewed on an iPhone (latest iOS) - navigation menus not shown.

**Comment by l01cd3v** [comment]
The report was not intended to be mobile-friendly. I chose to create an HTML report to make the output of the tool easy to use, not to allow remote access to the report. **If you decide to make the report remotely accessible, you should ensure to implement appropriate access controls as unauthorized access to this information would greatly aid a potential attacker.**

I am not a web designer and will not spend time porting the report to mobile. Closing the issue for now. Feel free to re-open it when/if you have a PR.  I'll accept a PR as long as it doesn't impact non-mobile browsing.
