### ISSUE TITLE
Security groups used to identify ElasticCache cluster are tagged as unused 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [nccgroup/Scout2#97]
We are using few security groups to identify ElastiCache clusters and Scout2 tags them as "Unused Security Groups". Is this a bug ? 

Thanks in Advance.
Himanshu

**Comment by l01cd3v** [comment]
This is due to the lack of support for ElasticCache, which is a known issue. The report's warning explicitly says "This group is not used by either EC2, RDS, or Redshift." to avoid confusion.

Marking as enhancement to add ElasticCache support

**Comment by l01cd3v** [comment]
Finally taken care of
